# Autogenerated code. DO NOT EDIT.
import typing

import wandb
from pydantic import BaseModel, Field


def _wandb_flatten(
    obj: BaseModel,
    paths: typing.Sequence[typing.Tuple[str, str]],
) -> typing.Dict[str, typing.Any]:
    """Map ``(attr_path, log_key)`` pairs on ``obj`` to a flat dict."""
    out: typing.Dict[str, typing.Any] = {}
    for attr_path, key in paths:
        cur: typing.Any = obj
        for part in attr_path.split('.'):
            cur = getattr(cur, part)
        if cur is None:
            continue
        out[key] = cur if isinstance(cur, (str, int, float, bool)) else str(cur)
    return out


class OptimizerConfigTest(BaseModel):
    """Nested optimizer knobs for tracking flatten tests."""

    learning_rate: float
    weight_decay: float


class RunConfigTest(BaseModel):
    """RUN_CONFIG for MLflow / W&B param + tag helpers."""

    run_name: str = Field(description='Human-readable run name (logged as a tag).')
    epochs: int
    optimizer: OptimizerConfigTest


class MetricSetTest(BaseModel):
    """METRIC_SET for MLflow / W&B metric helpers."""

    accuracy: float
    loss: float


_metric_set_test_METRIC_PATHS: typing.List[typing.Tuple[str, str]] = [
    ('accuracy', 'accuracy'),
    ('loss', 'loss'),
]


def metric_set_test_dict(metrics: MetricSetTest) -> typing.Dict[str, typing.Any]:
    """Flatten METRIC fields of ``MetricSetTest`` for ``wandb.log``."""
    return _wandb_flatten(metrics, _metric_set_test_METRIC_PATHS)


def log_metric_set_test(
    metrics: MetricSetTest,
    *,
    step: typing.Optional[int] = None,
) -> None:
    """Log ``MetricSetTest`` metrics via ``wandb.log``."""
    payload = metric_set_test_dict(metrics)
    if step is not None:
        wandb.log(payload, step=step)
    else:
        wandb.log(payload)


_run_config_test_PARAM_PATHS: typing.List[typing.Tuple[str, str]] = [
    ('epochs', 'epochs'),
    ('optimizer.learning_rate', 'optimizer.learning_rate'),
    ('optimizer.weight_decay', 'optimizer.weight_decay'),
]

_run_config_test_TAG_PATHS: typing.List[typing.Tuple[str, str]] = [('run_name', 'run_name')]


def run_config_test_config(config: RunConfigTest) -> typing.Dict[str, typing.Any]:
    """Flatten PARAM fields of ``RunConfigTest`` for ``wandb.init(config=...)``."""
    return _wandb_flatten(config, _run_config_test_PARAM_PATHS)


def init_run_config_test_run(
    config: RunConfigTest,
    *,
    project: typing.Optional[str] = None,
    name: typing.Optional[str] = None,
    **kwargs: typing.Any,
) -> typing.Any:
    """Initialize a W&B run for ``RunConfigTest`` with config + tags."""
    proj = project if project is not None else 'unit'
    run_name = name if name is not None else getattr(config, 'run_name', None)
    tags = [str(v) for v in _wandb_flatten(config, _run_config_test_TAG_PATHS).values()]
    return wandb.init(
        project=proj,
        name=run_name,
        config=run_config_test_config(config),
        tags=tags or None,
        **kwargs,
    )
