# Autogenerated code. DO NOT EDIT.
import typing

import argilla as rg
from pydantic import BaseModel, Field


class ReviewExampleTest(BaseModel):
    """Synthesis example for PydanticAI + Argilla flywheel tests."""

    id: str = Field(description='Stable identifier for the example (not shown as a primary Argilla field).',)
    instruction: str = Field(description='User-facing instruction or prompt to answer.')
    generation: str = Field(description='Model or human-written response to the instruction.',)
    quality: str = Field(description='Annotator quality label for the generation.')


def review_example_test_dataset_name() -> str:
    return 'review_examples'


def build_review_example_test_settings(
    *,
    client: typing.Optional[rg.Argilla] = None,
) -> rg.Settings:
    """Build Argilla ``Settings`` for ``ReviewExampleTest`` (FIELD + QUESTION only).

    Pass ``client=`` to avoid requiring a default Argilla API key at construction time.
    """
    settings_fields: typing.List[typing.Any] = []
    settings_fields.append(
        rg.TextField(name='instruction', required=True, client=client),
    )
    settings_fields.append(
        rg.TextField(name='generation', required=True, client=client),
    )
    settings_questions: typing.List[typing.Any] = []
    settings_questions.append(
        rg.LabelQuestion(
            name='quality',
            labels=['bad', 'good'],
            required=True,
            client=client,
        ),
    )
    return rg.Settings(fields=settings_fields, questions=settings_questions)


def to_review_example_test_record(row: ReviewExampleTest) -> rg.Record:
    """Map ``ReviewExampleTest`` to an Argilla ``Record`` by slot."""
    record_fields: typing.Dict[str, typing.Any] = {}
    record_fields['instruction'] = getattr(row, 'instruction')
    record_fields['generation'] = getattr(row, 'generation')
    record_metadata: typing.Dict[str, typing.Any] = {}
    record_metadata['id'] = getattr(row, 'id')
    suggestions: typing.List[typing.Any] = []
    _qval = getattr(row, 'quality', None)
    if _qval is not None:
        suggestions.append(rg.Suggestion(question_name='quality', value=_qval))
    return rg.Record(
        fields=record_fields,
        metadata=record_metadata or None,
        suggestions=suggestions or None,
    )


def from_review_example_test_record(record: rg.Record) -> ReviewExampleTest:
    """Map an Argilla ``Record`` back to ``ReviewExampleTest``."""
    data: typing.Dict[str, typing.Any] = {}
    data['instruction'] = record.fields.get('instruction')
    data['generation'] = record.fields.get('generation')
    data['id'] = (record.metadata or {}).get('id')
    # Question quality may live in responses/suggestions; best-effort
    data['quality'] = None
    for _s in (record.suggestions or []):
        if getattr(_s, 'question_name', None) == 'quality':
            data['quality'] = getattr(_s, 'value', None)
            break
    return ReviewExampleTest.model_validate(data)


REVIEW_EXAMPLE_TEST_ALIASES: typing.Dict[str, str] = {
    'id': 'id',
    'instruction': 'instruction',
    'generation': 'generation',
    'quality': 'quality',
}


def review_example_test_to_row_dict(
    row: ReviewExampleTest,
) -> typing.Dict[str, typing.Any]:
    return {REVIEW_EXAMPLE_TEST_ALIASES[k]: v for k, v in row.model_dump().items() if k in REVIEW_EXAMPLE_TEST_ALIASES}


def review_example_test_from_row_dict(
    data: typing.Dict[str, typing.Any],
) -> ReviewExampleTest:
    inv = {v: k for k, v in REVIEW_EXAMPLE_TEST_ALIASES.items()}
    mapped = {inv[k]: v for k, v in data.items() if k in inv}
    return ReviewExampleTest.model_validate(mapped)
