# Autogenerated code. DO NOT EDIT.
import typing

import py_gen_ml as pgml

from . import unit_base as base


class Int32TestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Int64TestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Uint32TestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Uint64TestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Sint32TestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Sint64TestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Fixed32TestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Fixed64TestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Sfixed32TestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Sfixed64TestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class BoolTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[bool] = None


class FloatTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[float] = None


class DoubleTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[float] = None


class StringTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[str] = None


class BytesTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[bytes] = None


class EnumTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[base.Enum] = None


class EnumDefaultTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[base.Enum] = None


class OneofTestPatch(pgml.YamlBaseModel):
    value: typing.Union[int, str]


class RepeatedTestPatch(pgml.YamlBaseModel):
    values: typing.Optional[typing.List[int]] = None


class OptionalTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Int32DefaultTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Int64DefaultTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Uint32DefaultTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Uint64DefaultTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Sint32DefaultTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Sint64DefaultTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Fixed32DefaultTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Fixed64DefaultTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Sfixed32DefaultTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class Sfixed64DefaultTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class BoolDefaultTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[bool] = None


class FloatDefaultTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[float] = None


class DoubleDefaultTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[float] = None


class StringDefaultTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[str] = None


class BytesDefaultTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[bytes] = None


class OneofDefaultTestPatch(pgml.YamlBaseModel):
    value: typing.Union[int, str]


class OptionalDefaultTestPatch(pgml.YamlBaseModel):
    value: typing.Optional[int] = None


class ExplicitCLIArgTestPatch(pgml.YamlBaseModel):
    bar: typing.Optional[str] = None


class ImplicitCLIArgTestPatch(pgml.YamlBaseModel):
    bar: typing.Optional[str] = None


class NestedFooTestPatch(pgml.YamlBaseModel):
    foo: typing.Optional[str] = None


class NestedBarTestPatch(pgml.YamlBaseModel):
    foo_0: typing.Optional[NestedFooTestPatch] = None
    foo_1: typing.Optional[NestedFooTestPatch] = None


class RepeatedNestedBarTestPatch(pgml.YamlBaseModel):
    bar: typing.Optional[typing.List[NestedBarTestPatch]] = None


class LanceDBNestedMetaPatch(pgml.YamlBaseModel):
    label: typing.Optional[str] = None


class LanceDBRecordTestPatch(pgml.YamlBaseModel):
    id: typing.Optional[str] = None
    embedding: typing.Optional[typing.List[float]] = None
    meta: typing.Optional[LanceDBNestedMetaPatch] = None


class PredictRequestTestPatch(pgml.YamlBaseModel):
    features: typing.Optional[typing.List[float]] = None


class PredictResponseTestPatch(pgml.YamlBaseModel):
    label: typing.Optional[int] = None
    score: typing.Optional[float] = None


class ClassifierServeConfigTestPatch(pgml.YamlBaseModel):
    url: typing.Optional[str] = None
    workers: typing.Optional[int] = None
    timeout_s: typing.Optional[float] = None
    workers_per_device: typing.Optional[int] = None
    accelerator: typing.Optional[str] = None


class ReviewExampleTestPatch(pgml.YamlBaseModel):
    """Synthesis example for PydanticAI + Argilla flywheel tests."""

    id: typing.Optional[str] = None
    """Stable identifier for the example (not shown as a primary Argilla field)."""

    instruction: typing.Optional[str] = None
    """User-facing instruction or prompt to answer."""

    generation: typing.Optional[str] = None
    """Model or human-written response to the instruction."""

    quality: typing.Optional[str] = None
    """Annotator quality label for the generation."""


class OptimizerConfigTestPatch(pgml.YamlBaseModel):
    """Nested optimizer knobs for tracking flatten tests."""

    learning_rate: typing.Optional[float] = None
    weight_decay: typing.Optional[float] = None


class RunConfigTestPatch(pgml.YamlBaseModel):
    """RUN_CONFIG for MLflow / W&B param + tag helpers."""

    run_name: typing.Optional[str] = None
    """Human-readable run name (logged as a tag)."""

    epochs: typing.Optional[int] = None
    optimizer: typing.Optional[OptimizerConfigTestPatch] = None


class MetricSetTestPatch(pgml.YamlBaseModel):
    """METRIC_SET for MLflow / W&B metric helpers."""

    accuracy: typing.Optional[float] = None
    loss: typing.Optional[float] = None


class ModelRegistryTestPatch(pgml.YamlBaseModel):
    """Model Registry contract (signature + register / resolve helpers)."""
