# Autogenerated code. DO NOT EDIT.
import typing

from lancedb.db import DBConnection
from lancedb.pydantic import LanceModel, Vector
from lancedb.table import LanceTable


class LanceDBNestedMeta(LanceModel):
    label: str


class LanceDBRecordTest(LanceModel):
    id: str
    embedding: Vector(4)
    meta: LanceDBNestedMeta


def lance_db_record_test_table_name() -> str:
    """Default LanceDB table name for :class:`LanceDBRecordTest`."""
    return 'lance_records'


def lance_db_record_test_merge_on() -> typing.List[str]:
    """Join columns for ``merge_insert`` / ``merge_rows`` (fields with ``(pgml.lancedb_field).merge_key``)."""
    return []


def create_lance_db_record_test_table(
    db: DBConnection,
    *,
    name: typing.Optional[str] = None,
    exist_ok: bool = True,
    **kwargs: typing.Any,
) -> LanceTable:
    """Create a LanceDB table whose schema is :class:`LanceDBRecordTest`.

    ``db`` is a connection from ``lancedb.connect(...)``.
    By default ``exist_ok=True`` opens the table if it already exists.
    Pass ``mode="overwrite"`` (via kwargs) to replace an existing table.
    Load rows for training via Arrow (``table.to_arrow()``) or LanceDB's
    ``Permutation`` streaming API, then hand tensors to
    ``torch.utils.data.DataLoader`` as needed.
    """
    return db.create_table(
        name or lance_db_record_test_table_name(),
        schema=LanceDBRecordTest,
        exist_ok=exist_ok,
        **kwargs,
    )
