# Autogenerated code. DO NOT EDIT.
import contextlib
import typing

import mlflow
from pydantic import BaseModel, Field


def _mlflow_flatten(
    obj: BaseModel,
    paths: typing.Sequence[typing.Tuple[str, str]],
) -> typing.Dict[str, typing.Any]:
    """Map ``(attr_path, log_key)`` pairs on ``obj`` to a flat dict."""
    out: typing.Dict[str, typing.Any] = {}
    for attr_path, key in paths:
        cur: typing.Any = obj
        for part in attr_path.split('.'):
            cur = getattr(cur, part)
        if cur is None:
            continue
        out[key] = cur if isinstance(cur, (str, int, float, bool)) else str(cur)
    return out


class OptimizerConfigTest(BaseModel):
    """Nested optimizer knobs for tracking flatten tests."""

    learning_rate: float
    weight_decay: float


class RunConfigTest(BaseModel):
    """RUN_CONFIG for MLflow / W&B param + tag helpers."""

    run_name: str = Field(description='Human-readable run name (logged as a tag).')
    epochs: int
    optimizer: OptimizerConfigTest


class MetricSetTest(BaseModel):
    """METRIC_SET for MLflow / W&B metric helpers."""

    accuracy: float
    loss: float


_metric_set_test_METRIC_PATHS: typing.List[typing.Tuple[str, str]] = [
    ('accuracy', 'accuracy'),
    ('loss', 'loss'),
]


def metric_set_test_metrics(metrics: MetricSetTest) -> typing.Dict[str, float]:
    """Flatten METRIC fields of ``MetricSetTest`` to floats for MLflow."""
    raw = _mlflow_flatten(metrics, _metric_set_test_METRIC_PATHS)
    return {k: float(v) for k, v in raw.items()}


def log_metric_set_test(
    metrics: MetricSetTest,
    *,
    step: typing.Optional[int] = None,
) -> None:
    """Log ``MetricSetTest`` metrics via ``mlflow.log_metrics``."""
    mlflow.log_metrics(metric_set_test_metrics(metrics), step=step)


_run_config_test_PARAM_PATHS: typing.List[typing.Tuple[str, str]] = [
    ('epochs', 'epochs'),
    ('optimizer.learning_rate', 'optimizer.learning_rate'),
    ('optimizer.weight_decay', 'optimizer.weight_decay'),
]

_run_config_test_TAG_PATHS: typing.List[typing.Tuple[str, str]] = [('run_name', 'run_name')]


def run_config_test_params(config: RunConfigTest) -> typing.Dict[str, typing.Any]:
    """Flatten PARAM (+ TAG as string params) fields of ``RunConfigTest`` for MLflow."""
    params = _mlflow_flatten(config, _run_config_test_PARAM_PATHS)
    tags = _mlflow_flatten(config, _run_config_test_TAG_PATHS)
    params.update({f'tag.{k}': v for k, v in tags.items()})
    return params


def log_run_config_test_params(config: RunConfigTest) -> None:
    """Log ``RunConfigTest`` PARAM/TAG fields via ``mlflow.log_params``."""
    mlflow.log_params(run_config_test_params(config))


@contextlib.contextmanager
def start_run_config_test_run(
    config: RunConfigTest,
    *,
    experiment_name: typing.Optional[str] = None,
    run_name: typing.Optional[str] = None,
) -> typing.Iterator[typing.Any]:
    """Start an MLflow run for ``RunConfigTest``, logging params on enter."""
    exp = experiment_name if experiment_name is not None else 'unit'
    if exp:
        mlflow.set_experiment(exp)
    name = run_name if run_name is not None else getattr(config, 'run_name', None)
    with mlflow.start_run(run_name=name) as run:
        log_run_config_test_params(config)
        for key, value in _mlflow_flatten(config, _run_config_test_TAG_PATHS).items():
            mlflow.set_tag(key, value)
        yield run
