# Autogenerated code. DO NOT EDIT.
import json
import typing

from pydantic import BaseModel, Field, create_model
from pydantic_ai import Agent
from pydantic_ai.models import Model
from pydantic_ai.output import NativeOutput


class ReviewExampleTest(BaseModel):
    """Synthesis example for PydanticAI + Argilla flywheel tests."""

    id: str = Field(description='Stable identifier for the example (not shown as a primary Argilla field).',)
    instruction: str = Field(description='User-facing instruction or prompt to answer.')
    generation: str = Field(description='Model or human-written response to the instruction.',)
    quality: str = Field(description='Annotator quality label for the generation.')


class ReviewExampleTestPartial(BaseModel):
    """Synthesis example for PydanticAI + Argilla flywheel tests."""

    id: typing.Optional[str] = Field(
        default=None,
        description='Stable identifier for the example (not shown as a primary Argilla field).',
    )
    instruction: typing.Optional[str] = Field(
        default=None,
        description='User-facing instruction or prompt to answer.',
    )
    generation: typing.Optional[str] = Field(
        default=None,
        description='Model or human-written response to the instruction.',
    )
    quality: typing.Optional[str] = Field(
        default=None,
        description='Annotator quality label for the generation.',
    )


_review_example_test_FIELD_DESCRIPTIONS: typing.Dict[str, str] = {
    'id': 'Stable identifier for the example (not shown as a primary Argilla field).',
    'instruction': 'User-facing instruction or prompt to answer.',
    'generation': 'Model or human-written response to the instruction.',
    'quality': 'Annotator quality label for the generation.',
}

_review_example_test_FIELD_ANNOTATIONS: typing.Dict[str, typing.Any] = {
    'id': ReviewExampleTest.model_fields['id'].annotation,
    'instruction': ReviewExampleTest.model_fields['instruction'].annotation,
    'generation': ReviewExampleTest.model_fields['generation'].annotation,
    'quality': ReviewExampleTest.model_fields['quality'].annotation,
}


def _review_example_test_gap_model(
    partial: ReviewExampleTestPartial,
) -> typing.Type[BaseModel]:
    """Build a Pydantic model containing only fields that are ``None`` on ``partial``."""
    fields: typing.Dict[str, typing.Any] = {}
    for name, annotation in _review_example_test_FIELD_ANNOTATIONS.items():
        if getattr(partial, name, None) is None:
            desc = _review_example_test_FIELD_DESCRIPTIONS.get(name)
            kwargs: typing.Dict[str, typing.Any] = {}
            if desc is not None:
                kwargs['description'] = desc
            fields[name] = (annotation, Field(**kwargs))
    return create_model(f'ReviewExampleTestGap', __base__=BaseModel, **fields)


def _review_example_test_examples_prompt(
    examples: typing.Sequence[ReviewExampleTestPartial],
) -> str:
    payload = [ex.model_dump(mode='json') for ex in examples]
    return 'Examples (JSON, null means unspecified):\n' + json.dumps(payload, indent=2)


def create_review_example_test_agent(
    model: typing.Union[str, Model],
    *,
    system_prompt: str,
    output_type: typing.Any,
) -> Agent:
    """Build a PydanticAI ``Agent`` for ``ReviewExampleTest`` using ``NativeOutput``."""
    return Agent(
        model,
        output_type=NativeOutput(
            output_type,
            name='ReviewExampleTest',
            description='Synthesis example for PydanticAI + Argilla flywheel tests.',
        ),
        system_prompt=system_prompt,
    )


async def synthesize_review_example_test(
    *,
    model: typing.Union[str, Model],
    system_prompt: str,
    count: int = 1,
    examples: typing.Optional[typing.Sequence[ReviewExampleTestPartial]] = None,
    incomplete: typing.Optional[typing.Sequence[ReviewExampleTestPartial]] = None,
    diversify_rounds: int = 0,
) -> typing.List[ReviewExampleTest]:
    """Synthesize ``ReviewExampleTest`` instances via PydanticAI ``NativeOutput``.

    Path A (``incomplete`` is None): generate ``count`` full models, optionally
    conditioned on ``examples`` (None-friendly partials). ``diversify_rounds``
    feeds prior outputs back as examples for subsequent rounds.

    Path B (``incomplete`` set): for each partial, ``create_model`` a gap schema
    of only ``None`` fields, fill via NativeOutput, merge to a full model.
    ``count`` is ignored; ``diversify_rounds`` must be 0.
    """
    if incomplete is not None and diversify_rounds > 0:
        raise ValueError('incomplete cannot be combined with diversify_rounds>0')
    if incomplete is not None:
        return await _review_example_test_complete(
            model=model,
            system_prompt=system_prompt,
            incomplete=incomplete,
            examples=examples,
        )
    return await _review_example_test_generate(
        model=model,
        system_prompt=system_prompt,
        count=count,
        examples=examples,
        diversify_rounds=diversify_rounds,
    )


def synthesize_review_example_test_sync(
    *,
    model: typing.Union[str, Model],
    system_prompt: str,
    count: int = 1,
    examples: typing.Optional[typing.Sequence[ReviewExampleTestPartial]] = None,
    incomplete: typing.Optional[typing.Sequence[ReviewExampleTestPartial]] = None,
    diversify_rounds: int = 0,
) -> typing.List[ReviewExampleTest]:
    """Sync wrapper around :func:`synthesize_review_example_test`."""
    import asyncio
    return asyncio.run(
        synthesize_review_example_test(
            model=model,
            system_prompt=system_prompt,
            count=count,
            examples=examples,
            incomplete=incomplete,
            diversify_rounds=diversify_rounds,
        ),
    )


async def _review_example_test_generate(
    *,
    model: typing.Union[str, Model],
    system_prompt: str,
    count: int,
    examples: typing.Optional[typing.Sequence[ReviewExampleTestPartial]],
    diversify_rounds: int,
) -> typing.List[ReviewExampleTest]:
    results: typing.List[ReviewExampleTest] = []
    example_buf: typing.List[ReviewExampleTestPartial] = list(examples or [])
    rounds = max(diversify_rounds, 0) + 1
    for round_idx in range(rounds):
        agent = create_review_example_test_agent(
            model,
            system_prompt=system_prompt,
            output_type=ReviewExampleTest,
        )
        for _ in range(count):
            parts = ['Generate one new instance matching the output schema.']
            if example_buf:
                if round_idx > 0:
                    parts.append('Prefer diversity relative to the examples.')
                parts.append(_review_example_test_examples_prompt(example_buf))
            run = await agent.run('\n\n'.join(parts))
            item = ReviewExampleTest.model_validate(run.output)
            results.append(item)
            example_buf.append(
                ReviewExampleTestPartial.model_validate(item.model_dump()),
            )
    return results


async def _review_example_test_complete(
    *,
    model: typing.Union[str, Model],
    system_prompt: str,
    incomplete: typing.Sequence[ReviewExampleTestPartial],
    examples: typing.Optional[typing.Sequence[ReviewExampleTestPartial]],
) -> typing.List[ReviewExampleTest]:
    results: typing.List[ReviewExampleTest] = []
    for partial in incomplete:
        gap_cls = _review_example_test_gap_model(partial)
        if not gap_cls.model_fields:
            results.append(
                ReviewExampleTest.model_validate(partial.model_dump(exclude_none=True)),
            )
            continue
        agent = create_review_example_test_agent(
            model,
            system_prompt=system_prompt,
            output_type=gap_cls,
        )
        parts = [
            'Fill only the missing fields for this partial example.',
            'Partial (JSON): ' + json.dumps(partial.model_dump(mode='json'), indent=2),
        ]
        if examples:
            parts.append(_review_example_test_examples_prompt(examples))
        run = await agent.run('\n\n'.join(parts))
        gap = run.output
        merged = {**partial.model_dump(exclude_none=True), **gap.model_dump()}
        results.append(ReviewExampleTest.model_validate(merged))
    return results
