# Autogenerated code. DO NOT EDIT.
import typing

import bentoml
import pgml_out_test.unit_base as base
from pydantic import BaseModel


class PredictRequestTest(BaseModel):
    features: typing.List[float]


class PredictResponseTest(BaseModel):
    label: int
    score: float


def classifier_test_service_kwargs(
    config: base.ClassifierServeConfigTest,
) -> typing.Dict[str, typing.Any]:
    """Map :class:`ClassifierServeConfigTest` fields to ``@bentoml.service`` kwargs."""
    kwargs: typing.Dict[str, typing.Any] = {}
    if getattr(config, 'workers', None) is not None:
        kwargs['workers'] = config.workers
    if getattr(config, 'timeout_s', None) is not None:
        kwargs['traffic'] = {'timeout': config.timeout_s}
    return kwargs


def create_classifier_test_service(
    *,
    predict: typing.Callable[[PredictRequestTest], PredictResponseTest],
    config: typing.Optional[base.ClassifierServeConfigTest] = None,
) -> typing.Any:
    """Build a ``@bentoml.service`` class for ``ClassifierTest``.

    Pass one callable per RPC; callables receive the request model and
    must return the response model. Do not edit the generated module—
    inject your model logic via these handlers.
    """
    cfg = config or base.ClassifierServeConfigTest()
    service_kwargs = classifier_test_service_kwargs(cfg)

    @bentoml.service(**service_kwargs)
    class ClassifierTest:

        @bentoml.api(
            route='/predict',
            name='predict',
            input_spec=PredictRequestTest,
            output_spec=PredictResponseTest,
        )
        def predict(self, **kwargs: typing.Any) -> PredictResponseTest:
            return predict(PredictRequestTest.model_validate(kwargs))

    return ClassifierTest


def call_classifier_test_predict_sync(
    request: PredictRequestTest,
    *,
    url: typing.Optional[str] = None,
    client: typing.Optional[bentoml.SyncHTTPClient] = None,
) -> PredictResponseTest:
    """Call ``ClassifierTest.Predict`` synchronously."""
    owns_client = client is None
    resolved_url = url or base.ClassifierServeConfigTest().url
    if client is None:
        if not resolved_url:
            raise ValueError('url is required when client is not provided')
        client = bentoml.SyncHTTPClient(resolved_url)
    try:
        raw = client.call('predict', **request.model_dump())
        return PredictResponseTest.model_validate(raw)
    finally:
        if owns_client:
            client.close()


async def call_classifier_test_predict_async(
    request: PredictRequestTest,
    *,
    url: typing.Optional[str] = None,
    client: typing.Optional[bentoml.AsyncHTTPClient] = None,
) -> PredictResponseTest:
    """Call ``ClassifierTest.Predict`` asynchronously."""
    owns_client = client is None
    resolved_url = url or base.ClassifierServeConfigTest().url
    if client is None:
        if not resolved_url:
            raise ValueError('url is required when client is not provided')
        client = bentoml.AsyncHTTPClient(resolved_url)
    try:
        raw = await client.call('predict', **request.model_dump())
        return PredictResponseTest.model_validate(raw)
    finally:
        if owns_client:
            await client.close()
