# Autogenerated code. DO NOT EDIT.
import typing
import httpx
import litserve as ls
from pydantic import BaseModel
import pgml_out_test.unit_base as base


class PredictRequestTest(BaseModel):
    features: typing.List[float]


class PredictResponseTest(BaseModel):
    label: int
    score: float


def classifier_test_server_kwargs(
    config: base.ClassifierServeConfigTest
) -> typing.Dict[str, typing.Any]:
    """Map :class:`ClassifierServeConfigTest` fields to ``ls.LitServer`` kwargs."""
    kwargs: typing.Dict[str, typing.Any] = {}
    if getattr(config, "accelerator", None) is not None:
        kwargs["accelerator"] = config.accelerator
    if getattr(config, "workers_per_device", None) is not None:
        kwargs["workers_per_device"] = config.workers_per_device
    if getattr(config, "timeout_s", None) is not None:
        kwargs["timeout"] = config.timeout_s
    return kwargs


class ClassifierTestPredictAPI(ls.LitAPI):
    """LitAPI for ``ClassifierTest.Predict``."""

    def __init__(
        self,
        predict: typing.Callable[[PredictRequestTest], PredictResponseTest],
        setup: typing.Optional[typing.Callable[[typing.Any, str], None]] = None
    ) -> None:
        super().__init__(api_path='/predict')
        self._predict = predict
        self._setup = setup

    def setup(self, device: str) -> None:
        if self._setup is not None:
            self._setup(self, device)

    def decode_request(self, request: PredictRequestTest) -> PredictRequestTest:
        if isinstance(request, PredictRequestTest):
            return request
        return PredictRequestTest.model_validate(request)

    def predict(self, x: PredictRequestTest) -> PredictResponseTest:
        return self._predict(x)

    def encode_response(self,
                        output: PredictResponseTest) -> typing.Dict[str, typing.Any]:
        if isinstance(output, PredictResponseTest):
            return output.model_dump()
        return PredictResponseTest.model_validate(output).model_dump()


def create_classifier_test_predict_api(
    *,
    predict: typing.Callable[[PredictRequestTest], PredictResponseTest],
    setup: typing.Optional[typing.Callable[[typing.Any, str], None]] = None
) -> ClassifierTestPredictAPI:
    """Build a ``ClassifierTestPredictAPI`` for ``ClassifierTest.Predict``.

    Pass the RPC handler as ``predict``; optionally ``setup(api, device)``
    for model load. Handlers should be module-level (picklable) for LitServe workers.
    Do not edit the generated module—inject logic via these callables.
    """
    return ClassifierTestPredictAPI(predict=predict, setup=setup)


def create_classifier_test_server(
    *,
    predict: typing.Callable[[PredictRequestTest], PredictResponseTest],
    setup: typing.Optional[typing.Callable[[typing.Any, str], None]] = None,
    config: typing.Optional[base.ClassifierServeConfigTest] = None,
    **server_kwargs: typing.Any
) -> ls.LitServer:
    """Build an ``ls.LitServer`` for ``ClassifierTest``.

    One ``LitAPI`` is created per RPC (distinct ``api_path``). Extra kwargs are
    forwarded to ``ls.LitServer`` and override mapped config fields.
    """
    cfg = config or base.ClassifierServeConfigTest()
    kwargs = classifier_test_server_kwargs(cfg)
    kwargs.update(server_kwargs)
    apis = [
        create_classifier_test_predict_api(predict=predict, setup=setup),
    ]
    return ls.LitServer(apis if len(apis) > 1 else apis[0], **kwargs)


def call_classifier_test_predict_sync(
    request: PredictRequestTest,
    *,
    url: typing.Optional[str] = None,
    client: typing.Optional[httpx.Client] = None
) -> PredictResponseTest:
    """Call ``ClassifierTest.Predict`` synchronously."""
    owns_client = client is None
    resolved_url = url or base.ClassifierServeConfigTest().url
    if not resolved_url:
        raise ValueError("url is required")
    endpoint = resolved_url.rstrip("/") + '/predict'
    if client is None:
        client = httpx.Client()
    try:
        response = client.post(endpoint, json=request.model_dump())
        response.raise_for_status()
        return PredictResponseTest.model_validate(response.json())
    finally:
        if owns_client:
            client.close()


async def call_classifier_test_predict_async(
    request: PredictRequestTest,
    *,
    url: typing.Optional[str] = None,
    client: typing.Optional[httpx.AsyncClient] = None
) -> PredictResponseTest:
    """Call ``ClassifierTest.Predict`` asynchronously."""
    owns_client = client is None
    resolved_url = url or base.ClassifierServeConfigTest().url
    if not resolved_url:
        raise ValueError("url is required")
    endpoint = resolved_url.rstrip("/") + '/predict'
    if client is None:
        client = httpx.AsyncClient()
    try:
        response = await client.post(endpoint, json=request.model_dump())
        response.raise_for_status()
        return PredictResponseTest.model_validate(response.json())
    finally:
        if owns_client:
            await client.aclose()
