# Autogenerated code. DO NOT EDIT.
import py_gen_ml as pgml
import typing

import pydantic
import typer

from . import unit_base as base


class ExplicitCLIArgTestArgs(pgml.YamlBaseModel):
    foo: typing.Annotated[
        typing.Optional[str],
        typer.Option(help="Maps to bar"),
        pydantic.Field(None),
        pgml.ArgRef("bar"),
    ]


class ImplicitCLIArgTestArgs(pgml.YamlBaseModel):
    bar: typing.Annotated[
        typing.Optional[str],
        typer.Option(help="Maps to bar"),
        pydantic.Field(None),
        pgml.ArgRef("bar"),
    ]
