# Autogenerated code. DO NOT EDIT.
import typing
import bentoml
from pydantic import BaseModel
import pgml_out.bentoml_demo_base as base


class PredictRequest(BaseModel):
    """Inference request features."""

    features: typing.List[float]


class PredictResponse(BaseModel):
    """Model prediction for a request."""

    label: int
    score: float


def classifier_service_kwargs(
    config: base.ClassifierServeConfig
) -> typing.Dict[str, typing.Any]:
    """Map :class:`ClassifierServeConfig` fields to ``@bentoml.service`` kwargs."""
    kwargs: typing.Dict[str, typing.Any] = {}
    if getattr(config, "workers", None) is not None:
        kwargs["workers"] = config.workers
    if getattr(config, "timeout_s", None) is not None:
        kwargs["traffic"] = {"timeout": config.timeout_s}
    return kwargs


def create_classifier_service(
    *,
    predict: typing.Callable[[PredictRequest], PredictResponse],
    config: typing.Optional[base.ClassifierServeConfig] = None
) -> typing.Any:
    """Build a ``@bentoml.service`` class for ``Classifier``.

    Pass one callable per RPC; callables receive the request model and
    must return the response model. Do not edit the generated module—
    inject your model logic via these handlers.
    """
    cfg = config or base.ClassifierServeConfig()
    service_kwargs = classifier_service_kwargs(cfg)

    @bentoml.service(**service_kwargs)
    class Classifier:

        @bentoml.api(
            route='/predict',
            name='predict',
            input_spec=PredictRequest,
            output_spec=PredictResponse
        )
        def predict(self, **kwargs: typing.Any) -> PredictResponse:
            return predict(PredictRequest.model_validate(kwargs))

    return Classifier


def call_classifier_predict_sync(
    request: PredictRequest,
    *,
    url: typing.Optional[str] = None,
    client: typing.Optional[bentoml.SyncHTTPClient] = None
) -> PredictResponse:
    """Call ``Classifier.Predict`` synchronously."""
    owns_client = client is None
    resolved_url = url or base.ClassifierServeConfig().url
    if client is None:
        if not resolved_url:
            raise ValueError("url is required when client is not provided")
        client = bentoml.SyncHTTPClient(resolved_url)
    try:
        raw = client.call('predict', **request.model_dump())
        return PredictResponse.model_validate(raw)
    finally:
        if owns_client:
            client.close()


async def call_classifier_predict_async(
    request: PredictRequest,
    *,
    url: typing.Optional[str] = None,
    client: typing.Optional[bentoml.AsyncHTTPClient] = None
) -> PredictResponse:
    """Call ``Classifier.Predict`` asynchronously."""
    owns_client = client is None
    resolved_url = url or base.ClassifierServeConfig().url
    if client is None:
        if not resolved_url:
            raise ValueError("url is required when client is not provided")
        client = bentoml.AsyncHTTPClient(resolved_url)
    try:
        raw = await client.call('predict', **request.model_dump())
        return PredictResponse.model_validate(raw)
    finally:
        if owns_client:
            await client.close()
