# Autogenerated code. DO NOT EDIT.
import py_gen_ml as pgml


class LinearBlockPatch(pgml.YamlBaseModel):
    """Linear block configuration"""

    in_features: int | None = None
    """Number of input features"""

    out_features: int | None = None
    """Number of output features"""

    bias: bool | None = None
    """Bias"""

    dropout: float | None = None
    """Dropout probability"""

    activation: str | None = None
    """Activation function"""


class MLPPatch(pgml.YamlBaseModel):
    """MLP configuration"""

    layers: list[LinearBlockPatch] | None = None
    """Linear blocks"""
