# Autogenerated code. DO NOT EDIT.
import py_gen_ml as pgml


class ReviewExample(pgml.YamlBaseModel):
    """
    A single instruction–response example for LLM synthesis and Argilla review.
    """

    id: str
    """Stable identifier stored as Argilla metadata (not a primary UI field)."""

    instruction: str
    """
    User-facing task prompt the model should answer. Clear comments become JSON
    Schema descriptions used by PydanticAI NativeOutput.
    """

    generation: str
    """Complete answer or generation for the instruction."""

    quality: str
    """Human quality judgment for the generation (Argilla LabelQuestion)."""
