# Autogenerated code. DO NOT EDIT.
import typing
import py_gen_ml as pgml


class ReviewExamplePatch(pgml.YamlBaseModel):
    """
    A single instruction–response example for LLM synthesis and Argilla review.
    """

    id: typing.Optional[str] = None
    """Stable identifier stored as Argilla metadata (not a primary UI field)."""

    instruction: typing.Optional[str] = None
    """
    User-facing task prompt the model should answer. Clear comments become JSON
    Schema descriptions used by PydanticAI NativeOutput.
    """

    generation: typing.Optional[str] = None
    """Complete answer or generation for the instruction."""

    quality: typing.Optional[str] = None
    """Human quality judgment for the generation (Argilla LabelQuestion)."""
