# Autogenerated code. DO NOT EDIT.
import typing
import py_gen_ml as pgml


class SampleMeta(pgml.YamlBaseModel):
    """Metadata nested under each training row."""

    label: str
    split_id: int


class EmbeddingSample(pgml.YamlBaseModel):
    """Root table schema for a LanceDB dataset of embedding rows."""

    id: str
    embedding: typing.List[float]
    """Fixed-size vector column for similarity search / training."""

    meta: SampleMeta
