# Autogenerated code. DO NOT EDIT.
import typing
import py_gen_ml as pgml


class PredictRequest(pgml.YamlBaseModel):
    """Inference request features."""

    features: typing.List[float]


class PredictResponse(pgml.YamlBaseModel):
    """Model prediction for a request."""

    label: int
    score: float


class ClassifierServeConfig(pgml.YamlBaseModel):
    """Serve / client settings for Classifier."""

    url: str = "http://localhost:8000"
    timeout_s: float = 30.0
    workers_per_device: int = 1
    accelerator: str = "cpu"
