# Autogenerated code. DO NOT EDIT.
import typing
import json
from pydantic import BaseModel, Field, create_model
from pydantic_ai import Agent
from pydantic_ai.models import Model
from pydantic_ai.output import NativeOutput


class SentimentExample(BaseModel):
    """
    Labeled movie-review example for sentiment classification. Field comments become
    JSON Schema descriptions for PydanticAI NativeOutput.
    """

    id: str = Field(
        description='Stable row id (Argilla metadata; not a primary UI field).'
    )
    source: str = Field(
        description=
        'Provenance of the row: "imdb" for seed reviews, "synthetic" for LLM-generated ones.'
    )
    text: str = Field(
        description=
        'Full movie-review text in the style of IMDB user reviews (may include spoilers, informal tone, and mixed praise/criticism). Used as the classifier input.'
    )
    sentiment: str = Field(
        description='Binary sentiment of the review: "negative" or "positive".'
    )


class SentimentExamplePartial(BaseModel):
    """
    Labeled movie-review example for sentiment classification. Field comments become
    JSON Schema descriptions for PydanticAI NativeOutput.
    """

    id: typing.Optional[str] = Field(
        default=None,
        description='Stable row id (Argilla metadata; not a primary UI field).'
    )
    source: typing.Optional[str] = Field(
        default=None,
        description=
        'Provenance of the row: "imdb" for seed reviews, "synthetic" for LLM-generated ones.'
    )
    text: typing.Optional[str] = Field(
        default=None,
        description=
        'Full movie-review text in the style of IMDB user reviews (may include spoilers, informal tone, and mixed praise/criticism). Used as the classifier input.'
    )
    sentiment: typing.Optional[str] = Field(
        default=None,
        description='Binary sentiment of the review: "negative" or "positive".'
    )


_sentiment_example_FIELD_DESCRIPTIONS: typing.Dict[str, str] = {
    'id':
        'Stable row id (Argilla metadata; not a primary UI field).',
    'source':
        'Provenance of the row: "imdb" for seed reviews, "synthetic" for LLM-generated ones.',
    'text':
        'Full movie-review text in the style of IMDB user reviews (may include spoilers, informal tone, and mixed praise/criticism). Used as the classifier input.',
    'sentiment':
        'Binary sentiment of the review: "negative" or "positive".',
}

_sentiment_example_FIELD_ANNOTATIONS: typing.Dict[str, typing.Any] = {
    'id': SentimentExample.model_fields['id'].annotation,
    'source': SentimentExample.model_fields['source'].annotation,
    'text': SentimentExample.model_fields['text'].annotation,
    'sentiment': SentimentExample.model_fields['sentiment'].annotation,
}


def _sentiment_example_gap_model(
    partial: SentimentExamplePartial
) -> typing.Type[BaseModel]:
    """Build a Pydantic model containing only fields that are ``None`` on ``partial``."""
    fields: typing.Dict[str, typing.Any] = {}
    for name, annotation in _sentiment_example_FIELD_ANNOTATIONS.items():
        if getattr(partial, name, None) is None:
            desc = _sentiment_example_FIELD_DESCRIPTIONS.get(name)
            kwargs: typing.Dict[str, typing.Any] = {}
            if desc is not None:
                kwargs["description"] = desc
            fields[name] = (annotation, Field(**kwargs))
    return create_model(f"SentimentExampleGap", __base__=BaseModel, **fields)


def _sentiment_example_examples_prompt(
    examples: typing.Sequence[SentimentExamplePartial]
) -> str:
    payload = [ex.model_dump(mode="json") for ex in examples]
    return "Examples (JSON, null means unspecified):\n" + json.dumps(payload, indent=2)


def create_sentiment_example_agent(
    model: typing.Union[str, Model], *, system_prompt: str, output_type: typing.Any
) -> Agent:
    """Build a PydanticAI ``Agent`` for ``SentimentExample`` using ``NativeOutput``."""
    return Agent(
        model,
        output_type=NativeOutput(
            output_type,
            name='SentimentExample',
            description=
            'Labeled movie-review example for sentiment classification. Field comments become JSON Schema descriptions for PydanticAI NativeOutput.'
        ),
        system_prompt=system_prompt
    )


async def synthesize_sentiment_example(
    *,
    model: typing.Union[str, Model],
    system_prompt: str,
    count: int = 1,
    examples: typing.Optional[typing.Sequence[SentimentExamplePartial]] = None,
    incomplete: typing.Optional[typing.Sequence[SentimentExamplePartial]] = None,
    diversify_rounds: int = 0
) -> typing.List[SentimentExample]:
    """Synthesize ``SentimentExample`` instances via PydanticAI ``NativeOutput``.

    Path A (``incomplete`` is None): generate ``count`` full models, optionally
    conditioned on ``examples`` (None-friendly partials). ``diversify_rounds``
    feeds prior outputs back as examples for subsequent rounds.

    Path B (``incomplete`` set): for each partial, ``create_model`` a gap schema
    of only ``None`` fields, fill via NativeOutput, merge to a full model.
    ``count`` is ignored; ``diversify_rounds`` must be 0.
    """
    if incomplete is not None and diversify_rounds > 0:
        raise ValueError("incomplete cannot be combined with diversify_rounds>0")
    if incomplete is not None:
        return await _sentiment_example_complete(
            model=model,
            system_prompt=system_prompt,
            incomplete=incomplete,
            examples=examples
        )
    return await _sentiment_example_generate(
        model=model,
        system_prompt=system_prompt,
        count=count,
        examples=examples,
        diversify_rounds=diversify_rounds
    )


def synthesize_sentiment_example_sync(
    *,
    model: typing.Union[str, Model],
    system_prompt: str,
    count: int = 1,
    examples: typing.Optional[typing.Sequence[SentimentExamplePartial]] = None,
    incomplete: typing.Optional[typing.Sequence[SentimentExamplePartial]] = None,
    diversify_rounds: int = 0
) -> typing.List[SentimentExample]:
    """Sync wrapper around :func:`synthesize_sentiment_example`."""
    import asyncio
    return asyncio.run(
        synthesize_sentiment_example(
            model=model,
            system_prompt=system_prompt,
            count=count,
            examples=examples,
            incomplete=incomplete,
            diversify_rounds=diversify_rounds
        )
    )


async def _sentiment_example_generate(
    *, model: typing.Union[str, Model], system_prompt: str, count: int,
    examples: typing.Optional[typing.Sequence[SentimentExamplePartial]],
    diversify_rounds: int
) -> typing.List[SentimentExample]:
    results: typing.List[SentimentExample] = []
    example_buf: typing.List[SentimentExamplePartial] = list(examples or [])
    rounds = max(diversify_rounds, 0) + 1
    for round_idx in range(rounds):
        agent = create_sentiment_example_agent(
            model, system_prompt=system_prompt, output_type=SentimentExample
        )
        for _ in range(count):
            parts = ["Generate one new instance matching the output schema."]
            if example_buf:
                if round_idx > 0:
                    parts.append("Prefer diversity relative to the examples.")
                parts.append(_sentiment_example_examples_prompt(example_buf))
            run = await agent.run("\n\n".join(parts))
            item = SentimentExample.model_validate(run.output)
            results.append(item)
            example_buf.append(
                SentimentExamplePartial.model_validate(item.model_dump())
            )
    return results


async def _sentiment_example_complete(
    *, model: typing.Union[str, Model], system_prompt: str,
    incomplete: typing.Sequence[SentimentExamplePartial],
    examples: typing.Optional[typing.Sequence[SentimentExamplePartial]]
) -> typing.List[SentimentExample]:
    results: typing.List[SentimentExample] = []
    for partial in incomplete:
        gap_cls = _sentiment_example_gap_model(partial)
        if not gap_cls.model_fields:
            results.append(
                SentimentExample.model_validate(partial.model_dump(exclude_none=True))
            )
            continue
        agent = create_sentiment_example_agent(
            model, system_prompt=system_prompt, output_type=gap_cls
        )
        parts = [
            "Fill only the missing fields for this partial example.",
            "Partial (JSON): " + json.dumps(partial.model_dump(mode="json"), indent=2),
        ]
        if examples:
            parts.append(_sentiment_example_examples_prompt(examples))
        run = await agent.run("\n\n".join(parts))
        gap = run.output
        merged = {**partial.model_dump(exclude_none=True), **gap.model_dump()}
        results.append(SentimentExample.model_validate(merged))
    return results
