# Autogenerated code. DO NOT EDIT.
import py_gen_ml as pgml


class SentimentExample(pgml.YamlBaseModel):
    """
    Labeled movie-review example for sentiment classification. Field comments become
    JSON Schema descriptions for PydanticAI NativeOutput.
    """

    id: str
    """Stable row id (Argilla metadata; not a primary UI field)."""

    source: str
    """
    Provenance of the row: "imdb" for seed reviews, "synthetic" for LLM-generated
    ones.
    """

    text: str
    """
    Full movie-review text in the style of IMDB user reviews (may include spoilers,
    informal tone, and mixed praise/criticism). Used as the classifier input.
    """

    sentiment: str
    """Binary sentiment of the review: "negative" or "positive"."""


class SentimentTrainConfig(pgml.YamlBaseModel):
    """Hyperparameters for a sentiment flywheel training run."""

    run_name: str = "sentiment"
    """Human-readable run name (logged as a tracker tag)."""

    synthesize_count: int = 4
    """Number of synthetic examples requested per diversify round."""

    diversify_rounds: int = 1
    """Extra synthesis rounds that feed prior outputs back as examples."""

    openai_model: str = "gpt-4o"
    """OpenAI / Azure deployment name used for synthesis."""

    test_size: float = 0.25
    """TF-IDF + logistic regression holdout fraction."""


class SentimentMetrics(pgml.YamlBaseModel):
    """Holdout metrics from the sentiment classifier."""

    accuracy: float
    n_train: int
    n_test: int
    n_labeled: int


class SentimentPredictRequest(pgml.YamlBaseModel):
    """Inference request for the online sentiment classifier."""

    id: str
    """Stable sample id (links prediction and feedback rows)."""

    text: str
    """Review text to classify."""


class SentimentPrediction(pgml.YamlBaseModel):
    """
    Model output for one scored review (separate from the labeled training row).
    """

    sample_id: str
    """Sample id matching SentimentPredictRequest.id."""

    text: str
    """Review text that was scored."""

    sentiment: str
    """Predicted sentiment: "negative" or "positive"."""

    score: float
    """Model confidence for the predicted class."""

    model_version: str
    """Deployed model / pipeline version tag."""


class SentimentFeedback(pgml.YamlBaseModel):
    """Human correction / re-label for a scored review."""

    sample_id: str
    """Sample id matching SentimentPrediction.sample_id."""

    text: str
    """Review text shown to the annotator."""

    predicted_sentiment: str
    """Model-predicted sentiment (for comparison; not the Argilla question)."""

    sentiment: str
    """
    Corrected sentiment after review: "negative" or "positive". When logging a draft
    from a prediction, set this to the predicted label so Argilla records it as a
    Suggestion.
    """

    source: str
    """Provenance: "model" for suggestion drafts, "human" after correction."""


class SentimentServeConfig(pgml.YamlBaseModel):
    """LitServe / client settings for SentimentClassifier."""

    url: str = "http://localhost:8000"
    timeout_s: float = 30.0
    workers_per_device: int = 1
    accelerator: str = "cpu"


class SentimentOnlineMetrics(pgml.YamlBaseModel):
    """Online-loop metrics (predictions vs human feedback)."""

    n_predictions: int
    n_feedback: int
    agreement_rate: float
