# Autogenerated code. DO NOT EDIT.
import typing
from lancedb.db import DBConnection
from lancedb.pydantic import LanceModel, Vector
from lancedb.table import LanceTable


class SentimentExample(LanceModel):
    """
    Labeled movie-review example for sentiment classification. Field comments become
    JSON Schema descriptions for PydanticAI NativeOutput.
    """

    id: str
    """Stable row id (Argilla metadata; not a primary UI field)."""

    source: str
    """
    Provenance of the row: "imdb" for seed reviews, "synthetic" for LLM-generated
    ones.
    """

    text: str
    """
    Full movie-review text in the style of IMDB user reviews (may include spoilers,
    informal tone, and mixed praise/criticism). Used as the classifier input.
    """

    sentiment: str
    """Binary sentiment of the review: "negative" or "positive"."""


class SentimentPrediction(LanceModel):
    """
    Model output for one scored review (separate from the labeled training row).
    """

    sample_id: str
    """Sample id matching SentimentPredictRequest.id."""

    text: str
    """Review text that was scored."""

    sentiment: str
    """Predicted sentiment: "negative" or "positive"."""

    score: float
    """Model confidence for the predicted class."""

    model_version: str
    """Deployed model / pipeline version tag."""


class SentimentFeedback(LanceModel):
    """Human correction / re-label for a scored review."""

    sample_id: str
    """Sample id matching SentimentPrediction.sample_id."""

    text: str
    """Review text shown to the annotator."""

    predicted_sentiment: str
    """Model-predicted sentiment (for comparison; not the Argilla question)."""

    sentiment: str
    """
    Corrected sentiment after review: "negative" or "positive". When logging a draft
    from a prediction, set this to the predicted label so Argilla records it as a
    Suggestion.
    """

    source: str
    """Provenance: "model" for suggestion drafts, "human" after correction."""


def sentiment_example_table_name() -> str:
    """Default LanceDB table name for :class:`SentimentExample`."""
    return 'sentiment_examples'


def sentiment_example_merge_on() -> typing.List[str]:
    """Join columns for ``merge_insert`` / ``merge_rows`` (fields with ``(pgml.lancedb_field).merge_key``)."""
    return ['id']


def create_sentiment_example_table(
    db: DBConnection,
    *,
    name: typing.Optional[str] = None,
    exist_ok: bool = True,
    **kwargs: typing.Any
) -> LanceTable:
    """Create a LanceDB table whose schema is :class:`SentimentExample`.

    ``db`` is a connection from ``lancedb.connect(...)``.
    By default ``exist_ok=True`` opens the table if it already exists.
    Pass ``mode="overwrite"`` (via kwargs) to replace an existing table.
    Load rows for training via Arrow (``table.to_arrow()``) or LanceDB's
    ``Permutation`` streaming API, then hand tensors to
    ``torch.utils.data.DataLoader`` as needed.
    """
    return db.create_table(
        name or sentiment_example_table_name(),
        schema=SentimentExample,
        exist_ok=exist_ok,
        **kwargs
    )


def sentiment_feedback_table_name() -> str:
    """Default LanceDB table name for :class:`SentimentFeedback`."""
    return 'sentiment_feedback'


def sentiment_feedback_merge_on() -> typing.List[str]:
    """Join columns for ``merge_insert`` / ``merge_rows`` (fields with ``(pgml.lancedb_field).merge_key``)."""
    return ['sample_id']


def create_sentiment_feedback_table(
    db: DBConnection,
    *,
    name: typing.Optional[str] = None,
    exist_ok: bool = True,
    **kwargs: typing.Any
) -> LanceTable:
    """Create a LanceDB table whose schema is :class:`SentimentFeedback`.

    ``db`` is a connection from ``lancedb.connect(...)``.
    By default ``exist_ok=True`` opens the table if it already exists.
    Pass ``mode="overwrite"`` (via kwargs) to replace an existing table.
    Load rows for training via Arrow (``table.to_arrow()``) or LanceDB's
    ``Permutation`` streaming API, then hand tensors to
    ``torch.utils.data.DataLoader`` as needed.
    """
    return db.create_table(
        name or sentiment_feedback_table_name(),
        schema=SentimentFeedback,
        exist_ok=exist_ok,
        **kwargs
    )


def sentiment_prediction_table_name() -> str:
    """Default LanceDB table name for :class:`SentimentPrediction`."""
    return 'sentiment_predictions'


def sentiment_prediction_merge_on() -> typing.List[str]:
    """Join columns for ``merge_insert`` / ``merge_rows`` (fields with ``(pgml.lancedb_field).merge_key``)."""
    return ['sample_id']


def create_sentiment_prediction_table(
    db: DBConnection,
    *,
    name: typing.Optional[str] = None,
    exist_ok: bool = True,
    **kwargs: typing.Any
) -> LanceTable:
    """Create a LanceDB table whose schema is :class:`SentimentPrediction`.

    ``db`` is a connection from ``lancedb.connect(...)``.
    By default ``exist_ok=True`` opens the table if it already exists.
    Pass ``mode="overwrite"`` (via kwargs) to replace an existing table.
    Load rows for training via Arrow (``table.to_arrow()``) or LanceDB's
    ``Permutation`` streaming API, then hand tensors to
    ``torch.utils.data.DataLoader`` as needed.
    """
    return db.create_table(
        name or sentiment_prediction_table_name(),
        schema=SentimentPrediction,
        exist_ok=exist_ok,
        **kwargs
    )
