# Autogenerated code. DO NOT EDIT.
import typing
import contextlib
import mlflow
from pydantic import BaseModel, Field


def _mlflow_flatten(
    obj: BaseModel, paths: typing.Sequence[typing.Tuple[str, str]]
) -> typing.Dict[str, typing.Any]:
    """Map ``(attr_path, log_key)`` pairs on ``obj`` to a flat dict."""
    out: typing.Dict[str, typing.Any] = {}
    for attr_path, key in paths:
        cur: typing.Any = obj
        for part in attr_path.split("."):
            cur = getattr(cur, part)
        if cur is None:
            continue
        out[key] = cur if isinstance(cur, (str, int, float, bool)) else str(cur)
    return out


class OptimizerCfg(BaseModel):
    learning_rate: float
    weight_decay: float


class TrainingConfig(BaseModel):
    """Training run hyperparameters for experiment tracking demos."""

    run_name: str = Field(description='Human-readable run name (tracker tag).')
    epochs: int
    optimizer: OptimizerCfg


class TrainMetrics(BaseModel):
    """Metrics logged once per step or epoch."""

    accuracy: float
    loss: float


_train_metrics_METRIC_PATHS: typing.List[typing.Tuple[str, str]] = [
    ('accuracy', 'accuracy'), ('loss', 'loss')
]


def train_metrics_metrics(metrics: TrainMetrics) -> typing.Dict[str, float]:
    """Flatten METRIC fields of ``TrainMetrics`` to floats for MLflow."""
    raw = _mlflow_flatten(metrics, _train_metrics_METRIC_PATHS)
    return {k: float(v) for k, v in raw.items()}


def log_train_metrics(
    metrics: TrainMetrics, *, step: typing.Optional[int] = None
) -> None:
    """Log ``TrainMetrics`` metrics via ``mlflow.log_metrics``."""
    mlflow.log_metrics(train_metrics_metrics(metrics), step=step)


_training_config_PARAM_PATHS: typing.List[typing.Tuple[str, str]] = [
    ('epochs', 'epochs'), ('optimizer.learning_rate', 'optimizer.learning_rate'),
    ('optimizer.weight_decay', 'optimizer.weight_decay')
]

_training_config_TAG_PATHS: typing.List[typing.Tuple[str,
                                                     str]] = [('run_name', 'run_name')]


def training_config_params(config: TrainingConfig) -> typing.Dict[str, typing.Any]:
    """Flatten PARAM (+ TAG as string params) fields of ``TrainingConfig`` for MLflow."""
    params = _mlflow_flatten(config, _training_config_PARAM_PATHS)
    tags = _mlflow_flatten(config, _training_config_TAG_PATHS)
    params.update({f"tag.{k}": v for k, v in tags.items()})
    return params


def log_training_config_params(config: TrainingConfig) -> None:
    """Log ``TrainingConfig`` PARAM/TAG fields via ``mlflow.log_params``."""
    mlflow.log_params(training_config_params(config))


@contextlib.contextmanager
def start_training_config_run(
    config: TrainingConfig,
    *,
    experiment_name: typing.Optional[str] = None,
    run_name: typing.Optional[str] = None
) -> typing.Iterator[typing.Any]:
    """Start an MLflow run for ``TrainingConfig``, logging params on enter."""
    exp = experiment_name if experiment_name is not None else 'demo'
    if exp:
        mlflow.set_experiment(exp)
    name = run_name if run_name is not None else getattr(config, 'run_name', None)
    with mlflow.start_run(run_name=name) as run:
        log_training_config_params(config)
        for key, value in _mlflow_flatten(config, _training_config_TAG_PATHS).items():
            mlflow.set_tag(key, value)
        yield run
