# Autogenerated code. DO NOT EDIT.
import typing
import py_gen_ml as pgml


class PredictRequestPatch(pgml.YamlBaseModel):
    """Inference request features."""

    features: typing.Optional[typing.List[float]] = None


class PredictResponsePatch(pgml.YamlBaseModel):
    """Model prediction for a request."""

    label: typing.Optional[int] = None
    score: typing.Optional[float] = None


class ClassifierServeConfigPatch(pgml.YamlBaseModel):
    """Serve / client settings for Classifier."""

    url: typing.Optional[str] = None
    workers: typing.Optional[int] = None
    timeout_s: typing.Optional[float] = None
