# Autogenerated code. DO NOT EDIT.
import typing
import py_gen_ml as pgml


class PredictRequest(pgml.YamlBaseModel):
    """Inference request features."""

    features: typing.List[float]


class PredictResponse(pgml.YamlBaseModel):
    """Model prediction for a request."""

    label: int
    score: float


class ClassifierServeConfig(pgml.YamlBaseModel):
    """Serve / client settings for Classifier."""

    url: str = "http://localhost:3000"
    workers: int = 1
    timeout_s: float = 60.0
