# Autogenerated code. DO NOT EDIT.
import py_gen_ml as pgml
import typing

import pydantic
import typer

from . import dataloader_base as base


class DataLoaderConfigArgs(pgml.YamlBaseModel):
    """DataLoader configuration"""
