# Autogenerated code. DO NOT EDIT.
import typing
import argilla as rg
from pydantic import BaseModel, Field


class ReviewExample(BaseModel):
    """
    A single instruction–response example for LLM synthesis and Argilla review.
    """

    id: str = Field(
        description=
        'Stable identifier stored as Argilla metadata (not a primary UI field).'
    )
    instruction: str = Field(
        description=
        'User-facing task prompt the model should answer. Clear comments become JSON Schema descriptions used by PydanticAI NativeOutput.'
    )
    generation: str = Field(
        description='Complete answer or generation for the instruction.'
    )
    quality: str = Field(
        description='Human quality judgment for the generation (Argilla LabelQuestion).'
    )


def review_example_dataset_name() -> str:
    return 'review_examples'


def build_review_example_settings(
    *, client: typing.Optional[rg.Argilla] = None
) -> rg.Settings:
    """Build Argilla ``Settings`` for ``ReviewExample`` (FIELD + QUESTION only).

    Pass ``client=`` to avoid requiring a default Argilla API key at construction time.
    """
    settings_fields: typing.List[typing.Any] = []
    settings_fields.append(
        rg.TextField(name='instruction', required=True, client=client)
    )
    settings_fields.append(
        rg.TextField(name='generation', required=True, client=client)
    )
    settings_questions: typing.List[typing.Any] = []
    settings_questions.append(
        rg.LabelQuestion(
            name='quality', labels=['bad', 'good'], required=True, client=client
        )
    )
    return rg.Settings(fields=settings_fields, questions=settings_questions)


def to_review_example_record(row: ReviewExample) -> rg.Record:
    """Map ``ReviewExample`` to an Argilla ``Record`` by slot."""
    record_fields: typing.Dict[str, typing.Any] = {}
    record_fields['instruction'] = getattr(row, 'instruction')
    record_fields['generation'] = getattr(row, 'generation')
    record_metadata: typing.Dict[str, typing.Any] = {}
    record_metadata['id'] = getattr(row, 'id')
    suggestions: typing.List[typing.Any] = []
    _qval = getattr(row, 'quality', None)
    if _qval is not None:
        suggestions.append(rg.Suggestion(question_name='quality', value=_qval))
    return rg.Record(
        fields=record_fields,
        metadata=record_metadata or None,
        suggestions=suggestions or None
    )


def from_review_example_record(record: rg.Record) -> ReviewExample:
    """Map an Argilla ``Record`` back to ``ReviewExample``."""
    data: typing.Dict[str, typing.Any] = {}
    data['instruction'] = record.fields.get('instruction')
    data['generation'] = record.fields.get('generation')
    data['id'] = (record.metadata or {}).get('id')
    # Question quality may live in responses/suggestions; best-effort
    data['quality'] = None
    for _s in (record.suggestions or []):
        if getattr(_s, "question_name", None) == 'quality':
            data['quality'] = getattr(_s, "value", None)
            break
    return ReviewExample.model_validate(data)


REVIEW_EXAMPLE_ALIASES: typing.Dict[str, str] = {
    'id': 'id',
    'instruction': 'instruction',
    'generation': 'generation',
    'quality': 'quality',
}


def review_example_to_row_dict(row: ReviewExample) -> typing.Dict[str, typing.Any]:
    return {
        REVIEW_EXAMPLE_ALIASES[k]: v
        for k, v in row.model_dump().items()
        if k in REVIEW_EXAMPLE_ALIASES
    }


def review_example_from_row_dict(data: typing.Dict[str, typing.Any]) -> ReviewExample:
    inv = {v: k for k, v in REVIEW_EXAMPLE_ALIASES.items()}
    mapped = {inv[k]: v for k, v in data.items() if k in inv}
    return ReviewExample.model_validate(mapped)
