# Autogenerated code. DO NOT EDIT.
import typing
import json
from pydantic import BaseModel, Field, create_model
from pydantic_ai import Agent
from pydantic_ai.models import Model
from pydantic_ai.output import NativeOutput


class ReviewExample(BaseModel):
    """
    A single instruction–response example for LLM synthesis and Argilla review.
    """

    id: str = Field(
        description=
        'Stable identifier stored as Argilla metadata (not a primary UI field).'
    )
    instruction: str = Field(
        description=
        'User-facing task prompt the model should answer. Clear comments become JSON Schema descriptions used by PydanticAI NativeOutput.'
    )
    generation: str = Field(
        description='Complete answer or generation for the instruction.'
    )
    quality: str = Field(
        description='Human quality judgment for the generation (Argilla LabelQuestion).'
    )


class ReviewExamplePartial(BaseModel):
    """
    A single instruction–response example for LLM synthesis and Argilla review.
    """

    id: typing.Optional[str] = Field(
        default=None,
        description=
        'Stable identifier stored as Argilla metadata (not a primary UI field).'
    )
    instruction: typing.Optional[str] = Field(
        default=None,
        description=
        'User-facing task prompt the model should answer. Clear comments become JSON Schema descriptions used by PydanticAI NativeOutput.'
    )
    generation: typing.Optional[str] = Field(
        default=None, description='Complete answer or generation for the instruction.'
    )
    quality: typing.Optional[str] = Field(
        default=None,
        description='Human quality judgment for the generation (Argilla LabelQuestion).'
    )


_review_example_FIELD_DESCRIPTIONS: typing.Dict[str, str] = {
    'id':
        'Stable identifier stored as Argilla metadata (not a primary UI field).',
    'instruction':
        'User-facing task prompt the model should answer. Clear comments become JSON Schema descriptions used by PydanticAI NativeOutput.',
    'generation':
        'Complete answer or generation for the instruction.',
    'quality':
        'Human quality judgment for the generation (Argilla LabelQuestion).',
}

_review_example_FIELD_ANNOTATIONS: typing.Dict[str, typing.Any] = {
    'id': ReviewExample.model_fields['id'].annotation,
    'instruction': ReviewExample.model_fields['instruction'].annotation,
    'generation': ReviewExample.model_fields['generation'].annotation,
    'quality': ReviewExample.model_fields['quality'].annotation,
}


def _review_example_gap_model(partial: ReviewExamplePartial) -> typing.Type[BaseModel]:
    """Build a Pydantic model containing only fields that are ``None`` on ``partial``."""
    fields: typing.Dict[str, typing.Any] = {}
    for name, annotation in _review_example_FIELD_ANNOTATIONS.items():
        if getattr(partial, name, None) is None:
            desc = _review_example_FIELD_DESCRIPTIONS.get(name)
            kwargs: typing.Dict[str, typing.Any] = {}
            if desc is not None:
                kwargs["description"] = desc
            fields[name] = (annotation, Field(**kwargs))
    return create_model(f"ReviewExampleGap", __base__=BaseModel, **fields)


def _review_example_examples_prompt(
    examples: typing.Sequence[ReviewExamplePartial]
) -> str:
    payload = [ex.model_dump(mode="json") for ex in examples]
    return "Examples (JSON, null means unspecified):\n" + json.dumps(payload, indent=2)


def create_review_example_agent(
    model: typing.Union[str, Model], *, system_prompt: str, output_type: typing.Any
) -> Agent:
    """Build a PydanticAI ``Agent`` for ``ReviewExample`` using ``NativeOutput``."""
    return Agent(
        model,
        output_type=NativeOutput(
            output_type,
            name='ReviewExample',
            description=
            'A single instruction–response example for LLM synthesis and Argilla review.'
        ),
        system_prompt=system_prompt
    )


async def synthesize_review_example(
    *,
    model: typing.Union[str, Model],
    system_prompt: str,
    count: int = 1,
    examples: typing.Optional[typing.Sequence[ReviewExamplePartial]] = None,
    incomplete: typing.Optional[typing.Sequence[ReviewExamplePartial]] = None,
    diversify_rounds: int = 0
) -> typing.List[ReviewExample]:
    """Synthesize ``ReviewExample`` instances via PydanticAI ``NativeOutput``.

    Path A (``incomplete`` is None): generate ``count`` full models, optionally
    conditioned on ``examples`` (None-friendly partials). ``diversify_rounds``
    feeds prior outputs back as examples for subsequent rounds.

    Path B (``incomplete`` set): for each partial, ``create_model`` a gap schema
    of only ``None`` fields, fill via NativeOutput, merge to a full model.
    ``count`` is ignored; ``diversify_rounds`` must be 0.
    """
    if incomplete is not None and diversify_rounds > 0:
        raise ValueError("incomplete cannot be combined with diversify_rounds>0")
    if incomplete is not None:
        return await _review_example_complete(
            model=model,
            system_prompt=system_prompt,
            incomplete=incomplete,
            examples=examples
        )
    return await _review_example_generate(
        model=model,
        system_prompt=system_prompt,
        count=count,
        examples=examples,
        diversify_rounds=diversify_rounds
    )


def synthesize_review_example_sync(
    *,
    model: typing.Union[str, Model],
    system_prompt: str,
    count: int = 1,
    examples: typing.Optional[typing.Sequence[ReviewExamplePartial]] = None,
    incomplete: typing.Optional[typing.Sequence[ReviewExamplePartial]] = None,
    diversify_rounds: int = 0
) -> typing.List[ReviewExample]:
    """Sync wrapper around :func:`synthesize_review_example`."""
    import asyncio
    return asyncio.run(
        synthesize_review_example(
            model=model,
            system_prompt=system_prompt,
            count=count,
            examples=examples,
            incomplete=incomplete,
            diversify_rounds=diversify_rounds
        )
    )


async def _review_example_generate(
    *, model: typing.Union[str, Model], system_prompt: str, count: int,
    examples: typing.Optional[typing.Sequence[ReviewExamplePartial]],
    diversify_rounds: int
) -> typing.List[ReviewExample]:
    results: typing.List[ReviewExample] = []
    example_buf: typing.List[ReviewExamplePartial] = list(examples or [])
    rounds = max(diversify_rounds, 0) + 1
    for round_idx in range(rounds):
        agent = create_review_example_agent(
            model, system_prompt=system_prompt, output_type=ReviewExample
        )
        for _ in range(count):
            parts = ["Generate one new instance matching the output schema."]
            if example_buf:
                if round_idx > 0:
                    parts.append("Prefer diversity relative to the examples.")
                parts.append(_review_example_examples_prompt(example_buf))
            run = await agent.run("\n\n".join(parts))
            item = ReviewExample.model_validate(run.output)
            results.append(item)
            example_buf.append(ReviewExamplePartial.model_validate(item.model_dump()))
    return results


async def _review_example_complete(
    *, model: typing.Union[str, Model], system_prompt: str,
    incomplete: typing.Sequence[ReviewExamplePartial],
    examples: typing.Optional[typing.Sequence[ReviewExamplePartial]]
) -> typing.List[ReviewExample]:
    results: typing.List[ReviewExample] = []
    for partial in incomplete:
        gap_cls = _review_example_gap_model(partial)
        if not gap_cls.model_fields:
            results.append(
                ReviewExample.model_validate(partial.model_dump(exclude_none=True))
            )
            continue
        agent = create_review_example_agent(
            model, system_prompt=system_prompt, output_type=gap_cls
        )
        parts = [
            "Fill only the missing fields for this partial example.",
            "Partial (JSON): " + json.dumps(partial.model_dump(mode="json"), indent=2),
        ]
        if examples:
            parts.append(_review_example_examples_prompt(examples))
        run = await agent.run("\n\n".join(parts))
        gap = run.output
        merged = {**partial.model_dump(exclude_none=True), **gap.model_dump()}
        results.append(ReviewExample.model_validate(merged))
    return results
