# Autogenerated code. DO NOT EDIT.
import typing
import py_gen_ml as pgml


class SampleMetaPatch(pgml.YamlBaseModel):
    """Metadata nested under each training row."""

    label: typing.Optional[str] = None
    split_id: typing.Optional[int] = None


class EmbeddingSamplePatch(pgml.YamlBaseModel):
    """Root table schema for a LanceDB dataset of embedding rows."""

    id: typing.Optional[str] = None
    embedding: typing.Optional[typing.List[float]] = None
    """Fixed-size vector column for similarity search / training."""

    meta: typing.Optional[SampleMetaPatch] = None
