# Autogenerated code. DO NOT EDIT.
import typing
from lancedb.db import DBConnection
from lancedb.pydantic import LanceModel, Vector
from lancedb.table import LanceTable


class SampleMeta(LanceModel):
    """Metadata nested under each training row."""

    label: str
    split_id: int


class EmbeddingSample(LanceModel):
    """Root table schema for a LanceDB dataset of embedding rows."""

    id: str
    embedding: Vector(8)
    """Fixed-size vector column for similarity search / training."""

    meta: SampleMeta


def embedding_sample_table_name() -> str:
    """Default LanceDB table name for :class:`EmbeddingSample`."""
    return 'embedding_samples'


def create_embedding_sample_table(
    db: DBConnection,
    *,
    name: typing.Optional[str] = None,
    **kwargs: typing.Any
) -> LanceTable:
    """Create a LanceDB table whose schema is :class:`EmbeddingSample`.

    ``db`` is a connection from ``lancedb.connect(...)``.
    Load rows for training via Arrow (``table.to_arrow()``) or LanceDB's
    ``Permutation`` streaming API, then hand tensors to
    ``torch.utils.data.DataLoader`` as needed.
    """
    return db.create_table(
        name or embedding_sample_table_name(), schema=EmbeddingSample, **kwargs
    )
