# Autogenerated code. DO NOT EDIT.
import py_gen_ml as pgml

from . import mlp_base as base


class MLPParsingDemoPatch(pgml.YamlBaseModel):
    """MLP is a simple multi-layer perceptron."""

    num_layers: int | None = None
    """Number of layers in the MLP."""

    num_units: int | None = None
    """Number of units in each layer."""

    activation: base.Activation | None = None
    """Activation function to use."""
