# Autogenerated code. DO NOT EDIT.
import typing
import contextlib
import mlflow
from pydantic import BaseModel, Field


def _mlflow_flatten(
    obj: BaseModel, paths: typing.Sequence[typing.Tuple[str, str]]
) -> typing.Dict[str, typing.Any]:
    """Map ``(attr_path, log_key)`` pairs on ``obj`` to a flat dict."""
    out: typing.Dict[str, typing.Any] = {}
    for attr_path, key in paths:
        cur: typing.Any = obj
        for part in attr_path.split("."):
            cur = getattr(cur, part)
        if cur is None:
            continue
        out[key] = cur if isinstance(cur, (str, int, float, bool)) else str(cur)
    return out


class SentimentTrainConfig(BaseModel):
    """Hyperparameters for a sentiment flywheel training run."""

    run_name: str = Field(
        description='Human-readable run name (logged as a tracker tag).'
    )
    synthesize_count: int = Field(
        description='Number of synthetic examples requested per diversify round.'
    )
    diversify_rounds: int = Field(
        description='Extra synthesis rounds that feed prior outputs back as examples.'
    )
    openai_model: str = Field(
        description='OpenAI / Azure deployment name used for synthesis.'
    )
    test_size: float = Field(
        description='TF-IDF + logistic regression holdout fraction.'
    )


class SentimentMetrics(BaseModel):
    """Holdout metrics from the sentiment classifier."""

    accuracy: float
    n_train: int
    n_test: int
    n_labeled: int


_sentiment_metrics_METRIC_PATHS: typing.List[typing.Tuple[str, str]] = [
    ('accuracy', 'accuracy'), ('n_train', 'n_train'), ('n_test', 'n_test'),
    ('n_labeled', 'n_labeled')
]


def sentiment_metrics_metrics(metrics: SentimentMetrics) -> typing.Dict[str, float]:
    """Flatten METRIC fields of ``SentimentMetrics`` to floats for MLflow."""
    raw = _mlflow_flatten(metrics, _sentiment_metrics_METRIC_PATHS)
    return {k: float(v) for k, v in raw.items()}


def log_sentiment_metrics(
    metrics: SentimentMetrics, *, step: typing.Optional[int] = None
) -> None:
    """Log ``SentimentMetrics`` metrics via ``mlflow.log_metrics``."""
    mlflow.log_metrics(sentiment_metrics_metrics(metrics), step=step)


_sentiment_train_config_PARAM_PATHS: typing.List[typing.Tuple[str, str]] = [
    ('synthesize_count', 'synthesize_count'), ('diversify_rounds', 'diversify_rounds'),
    ('openai_model', 'openai_model'), ('test_size', 'test_size')
]

_sentiment_train_config_TAG_PATHS: typing.List[typing.Tuple[str, str]] = [
    ('run_name', 'run_name')
]


def sentiment_train_config_params(
    config: SentimentTrainConfig
) -> typing.Dict[str, typing.Any]:
    """Flatten PARAM (+ TAG as string params) fields of ``SentimentTrainConfig`` for MLflow."""
    params = _mlflow_flatten(config, _sentiment_train_config_PARAM_PATHS)
    tags = _mlflow_flatten(config, _sentiment_train_config_TAG_PATHS)
    params.update({f"tag.{k}": v for k, v in tags.items()})
    return params


def log_sentiment_train_config_params(config: SentimentTrainConfig) -> None:
    """Log ``SentimentTrainConfig`` PARAM/TAG fields via ``mlflow.log_params``."""
    mlflow.log_params(sentiment_train_config_params(config))


@contextlib.contextmanager
def start_sentiment_train_config_run(
    config: SentimentTrainConfig,
    *,
    experiment_name: typing.Optional[str] = None,
    run_name: typing.Optional[str] = None
) -> typing.Iterator[typing.Any]:
    """Start an MLflow run for ``SentimentTrainConfig``, logging params on enter."""
    exp = experiment_name if experiment_name is not None else 'imdb_sentiment'
    if exp:
        mlflow.set_experiment(exp)
    name = run_name if run_name is not None else getattr(config, 'run_name', None)
    with mlflow.start_run(run_name=name) as run:
        log_sentiment_train_config_params(config)
        for key, value in _mlflow_flatten(config,
                                          _sentiment_train_config_TAG_PATHS).items():
            mlflow.set_tag(key, value)
        yield run
