# Autogenerated code. DO NOT EDIT.
import typing
import httpx
import litserve as ls
from pydantic import BaseModel
import pgml_out.sentiment_demo_base as base


class SentimentPredictRequest(BaseModel):
    """Inference request for the online sentiment classifier."""

    id: str
    """Stable sample id (links prediction and feedback rows)."""

    text: str
    """Review text to classify."""


class SentimentPrediction(BaseModel):
    """
    Model output for one scored review (separate from the labeled training row).
    """

    sample_id: str
    """Sample id matching SentimentPredictRequest.id."""

    text: str
    """Review text that was scored."""

    sentiment: str
    """Predicted sentiment: "negative" or "positive"."""

    score: float
    """Model confidence for the predicted class."""

    model_version: str
    """Deployed model / pipeline version tag."""


def sentiment_classifier_server_kwargs(
    config: base.SentimentServeConfig
) -> typing.Dict[str, typing.Any]:
    """Map :class:`SentimentServeConfig` fields to ``ls.LitServer`` kwargs."""
    kwargs: typing.Dict[str, typing.Any] = {}
    if getattr(config, "accelerator", None) is not None:
        kwargs["accelerator"] = config.accelerator
    if getattr(config, "workers_per_device", None) is not None:
        kwargs["workers_per_device"] = config.workers_per_device
    if getattr(config, "timeout_s", None) is not None:
        kwargs["timeout"] = config.timeout_s
    return kwargs


class SentimentClassifierPredictAPI(ls.LitAPI):
    """LitAPI for ``SentimentClassifier.Predict``."""

    def __init__(
        self,
        predict: typing.Callable[[SentimentPredictRequest], SentimentPrediction],
        setup: typing.Optional[typing.Callable[[typing.Any, str], None]] = None
    ) -> None:
        super().__init__(api_path='/predict')
        self._predict = predict
        self._setup = setup

    def setup(self, device: str) -> None:
        if self._setup is not None:
            self._setup(self, device)

    def decode_request(
        self, request: SentimentPredictRequest
    ) -> SentimentPredictRequest:
        if isinstance(request, SentimentPredictRequest):
            return request
        return SentimentPredictRequest.model_validate(request)

    def predict(self, x: SentimentPredictRequest) -> SentimentPrediction:
        return self._predict(x)

    def encode_response(self,
                        output: SentimentPrediction) -> typing.Dict[str, typing.Any]:
        if isinstance(output, SentimentPrediction):
            return output.model_dump()
        return SentimentPrediction.model_validate(output).model_dump()


def create_sentiment_classifier_predict_api(
    *,
    predict: typing.Callable[[SentimentPredictRequest], SentimentPrediction],
    setup: typing.Optional[typing.Callable[[typing.Any, str], None]] = None
) -> SentimentClassifierPredictAPI:
    """Build a ``SentimentClassifierPredictAPI`` for ``SentimentClassifier.Predict``.

    Pass the RPC handler as ``predict``; optionally ``setup(api, device)``
    for model load. Handlers should be module-level (picklable) for LitServe workers.
    Do not edit the generated module—inject logic via these callables.
    """
    return SentimentClassifierPredictAPI(predict=predict, setup=setup)


def create_sentiment_classifier_server(
    *,
    predict: typing.Callable[[SentimentPredictRequest], SentimentPrediction],
    setup: typing.Optional[typing.Callable[[typing.Any, str], None]] = None,
    config: typing.Optional[base.SentimentServeConfig] = None,
    **server_kwargs: typing.Any
) -> ls.LitServer:
    """Build an ``ls.LitServer`` for ``SentimentClassifier``.

    One ``LitAPI`` is created per RPC (distinct ``api_path``). Extra kwargs are
    forwarded to ``ls.LitServer`` and override mapped config fields.
    """
    cfg = config or base.SentimentServeConfig()
    kwargs = sentiment_classifier_server_kwargs(cfg)
    kwargs.update(server_kwargs)
    apis = [
        create_sentiment_classifier_predict_api(predict=predict, setup=setup),
    ]
    return ls.LitServer(apis if len(apis) > 1 else apis[0], **kwargs)


def call_sentiment_classifier_predict_sync(
    request: SentimentPredictRequest,
    *,
    url: typing.Optional[str] = None,
    client: typing.Optional[httpx.Client] = None
) -> SentimentPrediction:
    """Call ``SentimentClassifier.Predict`` synchronously."""
    owns_client = client is None
    resolved_url = url or base.SentimentServeConfig().url
    if not resolved_url:
        raise ValueError("url is required")
    endpoint = resolved_url.rstrip("/") + '/predict'
    if client is None:
        client = httpx.Client()
    try:
        response = client.post(endpoint, json=request.model_dump())
        response.raise_for_status()
        return SentimentPrediction.model_validate(response.json())
    finally:
        if owns_client:
            client.close()


async def call_sentiment_classifier_predict_async(
    request: SentimentPredictRequest,
    *,
    url: typing.Optional[str] = None,
    client: typing.Optional[httpx.AsyncClient] = None
) -> SentimentPrediction:
    """Call ``SentimentClassifier.Predict`` asynchronously."""
    owns_client = client is None
    resolved_url = url or base.SentimentServeConfig().url
    if not resolved_url:
        raise ValueError("url is required")
    endpoint = resolved_url.rstrip("/") + '/predict'
    if client is None:
        client = httpx.AsyncClient()
    try:
        response = await client.post(endpoint, json=request.model_dump())
        response.raise_for_status()
        return SentimentPrediction.model_validate(response.json())
    finally:
        if owns_client:
            await client.aclose()
