# Autogenerated code. DO NOT EDIT.
import typing
import argilla as rg
from pydantic import BaseModel, Field


class SentimentExample(BaseModel):
    """
    Labeled movie-review example for sentiment classification. Field comments become
    JSON Schema descriptions for PydanticAI NativeOutput.
    """

    id: str = Field(
        description='Stable row id (Argilla metadata; not a primary UI field).'
    )
    source: str = Field(
        description=
        'Provenance of the row: "imdb" for seed reviews, "synthetic" for LLM-generated ones.'
    )
    text: str = Field(
        description=
        'Full movie-review text in the style of IMDB user reviews (may include spoilers, informal tone, and mixed praise/criticism). Used as the classifier input.'
    )
    sentiment: str = Field(
        description='Binary sentiment of the review: "negative" or "positive".'
    )


class SentimentFeedback(BaseModel):
    """Human correction / re-label for a scored review."""

    sample_id: str = Field(
        description='Sample id matching SentimentPrediction.sample_id.'
    )
    text: str = Field(description='Review text shown to the annotator.')
    predicted_sentiment: str = Field(
        description=
        'Model-predicted sentiment (for comparison; not the Argilla question).'
    )
    sentiment: str = Field(
        description=
        'Corrected sentiment after review: "negative" or "positive". When logging a draft from a prediction, set this to the predicted label so Argilla records it as a Suggestion.'
    )
    source: str = Field(
        description='Provenance: "model" for suggestion drafts, "human" after correction.'
    )


def sentiment_example_dataset_name() -> str:
    return 'imdb_sentiment'


def build_sentiment_example_settings(
    *, client: typing.Optional[rg.Argilla] = None
) -> rg.Settings:
    """Build Argilla ``Settings`` for ``SentimentExample`` (FIELD + QUESTION only).

    Pass ``client=`` to avoid requiring a default Argilla API key at construction time.
    """
    settings_fields: typing.List[typing.Any] = []
    settings_fields.append(rg.TextField(name='text', required=True, client=client))
    settings_questions: typing.List[typing.Any] = []
    settings_questions.append(
        rg.LabelQuestion(
            name='sentiment',
            labels=['negative', 'positive'],
            required=True,
            client=client
        )
    )
    return rg.Settings(fields=settings_fields, questions=settings_questions)


def to_sentiment_example_record(row: SentimentExample) -> rg.Record:
    """Map ``SentimentExample`` to an Argilla ``Record`` by slot."""
    record_fields: typing.Dict[str, typing.Any] = {}
    record_fields['text'] = getattr(row, 'text')
    record_metadata: typing.Dict[str, typing.Any] = {}
    record_metadata['id'] = getattr(row, 'id')
    record_metadata['source'] = getattr(row, 'source')
    suggestions: typing.List[typing.Any] = []
    _qval = getattr(row, 'sentiment', None)
    if _qval is not None:
        suggestions.append(rg.Suggestion(question_name='sentiment', value=_qval))
    return rg.Record(
        fields=record_fields,
        metadata=record_metadata or None,
        suggestions=suggestions or None
    )


def from_sentiment_example_record(record: rg.Record) -> SentimentExample:
    """Map an Argilla ``Record`` back to ``SentimentExample``."""
    data: typing.Dict[str, typing.Any] = {}
    data['text'] = record.fields.get('text')
    data['id'] = (record.metadata or {}).get('id')
    data['source'] = (record.metadata or {}).get('source')
    # Question sentiment may live in responses/suggestions; best-effort
    data['sentiment'] = None
    for _s in (record.suggestions or []):
        if getattr(_s, "question_name", None) == 'sentiment':
            data['sentiment'] = getattr(_s, "value", None)
            break
    return SentimentExample.model_validate(data)


SENTIMENT_EXAMPLE_ALIASES: typing.Dict[str, str] = {
    'id': 'id',
    'source': 'source',
    'text': 'text',
    'sentiment': 'sentiment',
}


def sentiment_example_to_row_dict(
    row: SentimentExample
) -> typing.Dict[str, typing.Any]:
    return {
        SENTIMENT_EXAMPLE_ALIASES[k]: v
        for k, v in row.model_dump().items()
        if k in SENTIMENT_EXAMPLE_ALIASES
    }


def sentiment_example_from_row_dict(
    data: typing.Dict[str, typing.Any]
) -> SentimentExample:
    inv = {v: k for k, v in SENTIMENT_EXAMPLE_ALIASES.items()}
    mapped = {inv[k]: v for k, v in data.items() if k in inv}
    return SentimentExample.model_validate(mapped)


def sentiment_feedback_dataset_name() -> str:
    return 'imdb_sentiment_feedback'


def build_sentiment_feedback_settings(
    *, client: typing.Optional[rg.Argilla] = None
) -> rg.Settings:
    """Build Argilla ``Settings`` for ``SentimentFeedback`` (FIELD + QUESTION only).

    Pass ``client=`` to avoid requiring a default Argilla API key at construction time.
    """
    settings_fields: typing.List[typing.Any] = []
    settings_fields.append(rg.TextField(name='text', required=True, client=client))
    settings_questions: typing.List[typing.Any] = []
    settings_questions.append(
        rg.LabelQuestion(
            name='sentiment',
            labels=['negative', 'positive'],
            required=True,
            client=client
        )
    )
    return rg.Settings(fields=settings_fields, questions=settings_questions)


def to_sentiment_feedback_record(row: SentimentFeedback) -> rg.Record:
    """Map ``SentimentFeedback`` to an Argilla ``Record`` by slot."""
    record_fields: typing.Dict[str, typing.Any] = {}
    record_fields['text'] = getattr(row, 'text')
    record_metadata: typing.Dict[str, typing.Any] = {}
    record_metadata['sample_id'] = getattr(row, 'sample_id')
    record_metadata['predicted_sentiment'] = getattr(row, 'predicted_sentiment')
    record_metadata['source'] = getattr(row, 'source')
    suggestions: typing.List[typing.Any] = []
    _qval = getattr(row, 'sentiment', None)
    if _qval is not None:
        suggestions.append(rg.Suggestion(question_name='sentiment', value=_qval))
    return rg.Record(
        fields=record_fields,
        metadata=record_metadata or None,
        suggestions=suggestions or None
    )


def from_sentiment_feedback_record(record: rg.Record) -> SentimentFeedback:
    """Map an Argilla ``Record`` back to ``SentimentFeedback``."""
    data: typing.Dict[str, typing.Any] = {}
    data['text'] = record.fields.get('text')
    data['sample_id'] = (record.metadata or {}).get('sample_id')
    data['predicted_sentiment'] = (record.metadata or {}).get('predicted_sentiment')
    data['source'] = (record.metadata or {}).get('source')
    # Question sentiment may live in responses/suggestions; best-effort
    data['sentiment'] = None
    for _s in (record.suggestions or []):
        if getattr(_s, "question_name", None) == 'sentiment':
            data['sentiment'] = getattr(_s, "value", None)
            break
    return SentimentFeedback.model_validate(data)
