# Autogenerated code. DO NOT EDIT.
import typing
from lancedb.db import DBConnection
from lancedb.pydantic import LanceModel, Vector
from lancedb.table import LanceTable


class SentimentExample(LanceModel):
    """
    Labeled movie-review example for sentiment classification. Field comments become
    JSON Schema descriptions for PydanticAI NativeOutput.
    """

    id: str
    """Stable row id (Argilla metadata; not a primary UI field)."""

    source: str
    """
    Provenance of the row: "imdb" for seed reviews, "synthetic" for LLM-generated
    ones.
    """

    text: str
    """
    Full movie-review text in the style of IMDB user reviews (may include spoilers,
    informal tone, and mixed praise/criticism). Used as the classifier input.
    """

    sentiment: str
    """Binary sentiment of the review: "negative" or "positive"."""


def sentiment_example_table_name() -> str:
    """Default LanceDB table name for :class:`SentimentExample`."""
    return 'sentiment_examples'


def create_sentiment_example_table(
    db: DBConnection,
    *,
    name: typing.Optional[str] = None,
    **kwargs: typing.Any
) -> LanceTable:
    """Create a LanceDB table whose schema is :class:`SentimentExample`.

    ``db`` is a connection from ``lancedb.connect(...)``.
    Load rows for training via Arrow (``table.to_arrow()``) or LanceDB's
    ``Permutation`` streaming API, then hand tensors to
    ``torch.utils.data.DataLoader`` as needed.
    """
    return db.create_table(
        name or sentiment_example_table_name(), schema=SentimentExample, **kwargs
    )
