# Autogenerated code. DO NOT EDIT.
import py_gen_ml as pgml


class SentimentExample(pgml.YamlBaseModel):
    """
    Labeled movie-review example for sentiment classification. Field comments become
    JSON Schema descriptions for PydanticAI NativeOutput.
    """

    id: str
    """Stable row id (Argilla metadata; not a primary UI field)."""

    source: str
    """
    Provenance of the row: "imdb" for seed reviews, "synthetic" for LLM-generated
    ones.
    """

    text: str
    """
    Full movie-review text in the style of IMDB user reviews (may include spoilers,
    informal tone, and mixed praise/criticism). Used as the classifier input.
    """

    sentiment: str
    """Binary sentiment of the review: "negative" or "positive"."""
