# Autogenerated code. DO NOT EDIT.
import typing
import py_gen_ml as pgml


class SentimentExamplePatch(pgml.YamlBaseModel):
    """
    Labeled movie-review example for sentiment classification. Field comments become
    JSON Schema descriptions for PydanticAI NativeOutput.
    """

    id: typing.Optional[str] = None
    """Stable row id (Argilla metadata; not a primary UI field)."""

    source: typing.Optional[str] = None
    """
    Provenance of the row: "imdb" for seed reviews, "synthetic" for LLM-generated
    ones.
    """

    text: typing.Optional[str] = None
    """
    Full movie-review text in the style of IMDB user reviews (may include spoilers,
    informal tone, and mixed praise/criticism). Used as the classifier input.
    """

    sentiment: typing.Optional[str] = None
    """Binary sentiment of the review: "negative" or "positive"."""


class SentimentTrainConfigPatch(pgml.YamlBaseModel):
    """Hyperparameters for a sentiment flywheel training run."""

    run_name: typing.Optional[str] = None
    """Human-readable run name (logged as a tracker tag)."""

    synthesize_count: typing.Optional[int] = None
    """Number of synthetic examples requested per diversify round."""

    diversify_rounds: typing.Optional[int] = None
    """Extra synthesis rounds that feed prior outputs back as examples."""

    openai_model: typing.Optional[str] = None
    """OpenAI / Azure deployment name used for synthesis."""

    test_size: typing.Optional[float] = None
    """TF-IDF + logistic regression holdout fraction."""


class SentimentMetricsPatch(pgml.YamlBaseModel):
    """Holdout metrics from the sentiment classifier."""

    accuracy: typing.Optional[float] = None
    n_train: typing.Optional[int] = None
    n_test: typing.Optional[int] = None
    n_labeled: typing.Optional[int] = None


class SentimentPredictRequestPatch(pgml.YamlBaseModel):
    """Inference request for the online sentiment classifier."""

    id: typing.Optional[str] = None
    """Stable sample id (links prediction and feedback rows)."""

    text: typing.Optional[str] = None
    """Review text to classify."""


class SentimentPredictionPatch(pgml.YamlBaseModel):
    """
    Model output for one scored review (separate from the labeled training row).
    """

    sample_id: typing.Optional[str] = None
    """Sample id matching SentimentPredictRequest.id."""

    text: typing.Optional[str] = None
    """Review text that was scored."""

    sentiment: typing.Optional[str] = None
    """Predicted sentiment: "negative" or "positive"."""

    score: typing.Optional[float] = None
    """Model confidence for the predicted class."""

    model_version: typing.Optional[str] = None
    """Deployed model / pipeline version tag."""


class SentimentFeedbackPatch(pgml.YamlBaseModel):
    """Human correction / re-label for a scored review."""

    sample_id: typing.Optional[str] = None
    """Sample id matching SentimentPrediction.sample_id."""

    text: typing.Optional[str] = None
    """Review text shown to the annotator."""

    predicted_sentiment: typing.Optional[str] = None
    """Model-predicted sentiment (for comparison; not the Argilla question)."""

    sentiment: typing.Optional[str] = None
    """
    Corrected sentiment after review: "negative" or "positive". When logging a draft
    from a prediction, set this to the predicted label so Argilla records it as a
    Suggestion.
    """

    source: typing.Optional[str] = None
    """Provenance: "model" for suggestion drafts, "human" after correction."""


class SentimentServeConfigPatch(pgml.YamlBaseModel):
    """LitServe / client settings for SentimentClassifier."""

    url: typing.Optional[str] = None
    timeout_s: typing.Optional[float] = None
    workers_per_device: typing.Optional[int] = None
    accelerator: typing.Optional[str] = None


class SentimentOnlineMetricsPatch(pgml.YamlBaseModel):
    """Online-loop metrics (predictions vs human feedback)."""

    n_predictions: typing.Optional[int] = None
    n_feedback: typing.Optional[int] = None
    agreement_rate: typing.Optional[float] = None
