# Autogenerated code. DO NOT EDIT.
import py_gen_ml as pgml
import typing

import pydantic
import typer

from . import sentiment_demo_base as base


class SentimentTrainConfigArgs(pgml.YamlBaseModel):
    """Hyperparameters for a sentiment flywheel training run."""

    run_name: typing.Annotated[
        typing.Optional[str],
        typer.Option(
            help="Human-readable run name (logged as a tracker tag). Maps to 'run_name'"
        ),
        pydantic.Field(None),
        pgml.ArgRef("run_name"),
    ]
    """Human-readable run name (logged as a tracker tag)."""

    synthesize_count: typing.Annotated[
        typing.Optional[int],
        typer.Option(
            help=
            "Number of synthetic examples requested per diversify round. Maps to 'synthesize_count'"
        ),
        pydantic.Field(None),
        pgml.ArgRef("synthesize_count"),
    ]
    """Number of synthetic examples requested per diversify round."""

    diversify_rounds: typing.Annotated[
        typing.Optional[int],
        typer.Option(
            help=
            "Extra synthesis rounds that feed prior outputs back as examples. Maps to 'diversify_rounds'"
        ),
        pydantic.Field(None),
        pgml.ArgRef("diversify_rounds"),
    ]
    """Extra synthesis rounds that feed prior outputs back as examples."""

    openai_model: typing.Annotated[
        typing.Optional[str],
        typer.Option(
            help=
            "OpenAI / Azure deployment name used for synthesis. Maps to 'openai_model'"
        ),
        pydantic.Field(None),
        pgml.ArgRef("openai_model"),
    ]
    """OpenAI / Azure deployment name used for synthesis."""

    test_size: typing.Annotated[
        typing.Optional[float],
        typer.Option(
            help="TF-IDF + logistic regression holdout fraction. Maps to 'test_size'"
        ),
        pydantic.Field(None),
        pgml.ArgRef("test_size"),
    ]
    """TF-IDF + logistic regression holdout fraction."""
