# Autogenerated code. DO NOT EDIT.
import typing
import py_gen_ml as pgml


class OptimizerCfgPatch(pgml.YamlBaseModel):
    learning_rate: typing.Optional[float] = None
    weight_decay: typing.Optional[float] = None


class TrainingConfigPatch(pgml.YamlBaseModel):
    """Training run hyperparameters for experiment tracking demos."""

    run_name: typing.Optional[str] = None
    """Human-readable run name (tracker tag)."""

    epochs: typing.Optional[int] = None
    optimizer: typing.Optional[OptimizerCfgPatch] = None


class TrainMetricsPatch(pgml.YamlBaseModel):
    """Metrics logged once per step or epoch."""

    accuracy: typing.Optional[float] = None
    loss: typing.Optional[float] = None
