# Autogenerated code. DO NOT EDIT.
import py_gen_ml as pgml


class OptimizerCfg(pgml.YamlBaseModel):
    learning_rate: float
    weight_decay: float


class TrainingConfig(pgml.YamlBaseModel):
    """Training run hyperparameters for experiment tracking demos."""

    run_name: str
    """Human-readable run name (tracker tag)."""

    epochs: int
    optimizer: OptimizerCfg


class TrainMetrics(pgml.YamlBaseModel):
    """Metrics logged once per step or epoch."""

    accuracy: float
    loss: float
