# Autogenerated code. DO NOT EDIT.
import typing
import wandb
from pydantic import BaseModel, Field


def _wandb_flatten(
    obj: BaseModel, paths: typing.Sequence[typing.Tuple[str, str]]
) -> typing.Dict[str, typing.Any]:
    """Map ``(attr_path, log_key)`` pairs on ``obj`` to a flat dict."""
    out: typing.Dict[str, typing.Any] = {}
    for attr_path, key in paths:
        cur: typing.Any = obj
        for part in attr_path.split("."):
            cur = getattr(cur, part)
        if cur is None:
            continue
        out[key] = cur if isinstance(cur, (str, int, float, bool)) else str(cur)
    return out


class OptimizerCfg(BaseModel):
    learning_rate: float
    weight_decay: float


class TrainingConfig(BaseModel):
    """Training run hyperparameters for experiment tracking demos."""

    run_name: str = Field(description='Human-readable run name (tracker tag).')
    epochs: int
    optimizer: OptimizerCfg


class TrainMetrics(BaseModel):
    """Metrics logged once per step or epoch."""

    accuracy: float
    loss: float


_train_metrics_METRIC_PATHS: typing.List[typing.Tuple[str, str]] = [
    ('accuracy', 'accuracy'), ('loss', 'loss')
]


def train_metrics_dict(metrics: TrainMetrics) -> typing.Dict[str, typing.Any]:
    """Flatten METRIC fields of ``TrainMetrics`` for ``wandb.log``."""
    return _wandb_flatten(metrics, _train_metrics_METRIC_PATHS)


def log_train_metrics(
    metrics: TrainMetrics, *, step: typing.Optional[int] = None
) -> None:
    """Log ``TrainMetrics`` metrics via ``wandb.log``."""
    payload = train_metrics_dict(metrics)
    if step is not None:
        wandb.log(payload, step=step)
    else:
        wandb.log(payload)


_training_config_PARAM_PATHS: typing.List[typing.Tuple[str, str]] = [
    ('epochs', 'epochs'), ('optimizer.learning_rate', 'optimizer.learning_rate'),
    ('optimizer.weight_decay', 'optimizer.weight_decay')
]

_training_config_TAG_PATHS: typing.List[typing.Tuple[str,
                                                     str]] = [('run_name', 'run_name')]


def training_config_config(config: TrainingConfig) -> typing.Dict[str, typing.Any]:
    """Flatten PARAM fields of ``TrainingConfig`` for ``wandb.init(config=...)``."""
    return _wandb_flatten(config, _training_config_PARAM_PATHS)


def init_training_config_run(
    config: TrainingConfig,
    *,
    project: typing.Optional[str] = None,
    name: typing.Optional[str] = None,
    **kwargs: typing.Any
) -> typing.Any:
    """Initialize a W&B run for ``TrainingConfig`` with config + tags."""
    proj = project if project is not None else 'demo'
    run_name = name if name is not None else getattr(config, 'run_name', None)
    tags = [str(v) for v in _wandb_flatten(config, _training_config_TAG_PATHS).values()]
    return wandb.init(
        project=proj,
        name=run_name,
        config=training_config_config(config),
        tags=tags or None,
        **kwargs
    )
