from typing import Final

BASE_MODEL_ALIAS: Final[str] = 'base'
SWEEP_MODEL_ALIAS: Final[str] = 'sweep'
PATCH_MODEL_ALIAS: Final[str] = 'patch'
CLI_ARGS_ALIAS: Final[str] = 'cli_args'
LANCEDB_ALIAS: Final[str] = 'lancedb'
BENTOML_ALIAS: Final[str] = 'bentoml'
LITSERVE_ALIAS: Final[str] = 'litserve'
PYDANTIC_AI_ALIAS: Final[str] = 'pydantic_ai'
ARGILLA_ALIAS: Final[str] = 'argilla'
MLFLOW_ALIAS: Final[str] = 'mlflow'
WANDB_ALIAS: Final[str] = 'wandb'
PGML_ALIAS: Final[str] = 'pgml'

BASE_SUFFIX: Final[str] = '_base.py'
PATCH_SUFFIX: Final[str] = '_patch.py'
SWEEP_SUFFIX: Final[str] = '_sweep.py'
CLI_ARGS_SUFFIX: Final[str] = '_cli_args.py'
LANCEDB_SUFFIX: Final[str] = '_lancedb.py'
BENTOML_SUFFIX: Final[str] = '_bentoml.py'
LITSERVE_SUFFIX: Final[str] = '_litserve.py'
PYDANTIC_AI_SUFFIX: Final[str] = '_pydantic_ai.py'
ARGILLA_SUFFIX: Final[str] = '_argilla.py'
MLFLOW_SUFFIX: Final[str] = '_mlflow.py'
WANDB_SUFFIX: Final[str] = '_wandb.py'
