on:
  workflow_dispatch:
jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit-and-test.yml
  release:
    needs:
    - pre-commit
    permissions:
      id-token: write
      contents: write
    uses: ./.github/workflows/release.yml
