on:
  pull_request:
jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit-and-test.yml
  release:
    permissions:
      id-token: write
    needs: pre-commit
    uses: ./.github/workflows/release.yml
