on:
  push:
    branches:
    - main
jobs:
  pre-commit:
    runs-on: ubuntu-latest
    steps:
    - uses: ./.github/workflows/pre-commit-and-test.yml
  release:
    permissions:
      id-token: write
    uses: ./.github/workflows/release.yml
