on:
  push:
    branches:
    - main
jobs:
  pre-commit:
    uses: ./.github/workflows/pre-commit-and-test.yml
  release:
    needs:
    - pre-commit
    permissions:
      id-token: write
    uses: ./.github/workflows/release.yml
